"use client"

import React from "react"
import { useLocalization } from "@/app/context/LocalizationContext"

const getVariableCosts = (t: (key: string) => string) => [
  { 
    label: t('pricing.variable.label1') || "Partner ICP Lead Cost", 
    price: "50¢",
    description: t('pricing.variable.cost1') || "Cost per highly qualified lead generated by AI based on your Ideal Partner Profile."
  },
  { 
    label: t('pricing.variable.label2') || "Outsourced Partner Meeting", 
    price: "20$",
    description: t('pricing.variable.cost2') || "Fixed fee for each initial meeting scheduled to recruit a new partner."
  },
  { 
    label: t('pricing.variable.label3') || "Successful Partner Recruitment", 
    price: "10$",
    description: t('pricing.variable.cost3') || "Bonus applied when the meeting results in signing a new partner."
  },
  { 
    label: t('pricing.variable.label4') || "API Call / Deep Research", 
    price: "1¢",
    description: t('pricing.variable.cost4') || "Cost per AI API request or deep web data extraction."
  },
  { 
    label: t('pricing.variable.label5') || "1M Input Tokens", 
    price: "1$",
    description: t('pricing.variable.cost5') || "Processing cost for 1 million text tokens sent to our AI models."
  },
  { 
    label: t('pricing.variable.label6') || "1M Output Tokens", 
    price: "20$",
    description: t('pricing.variable.cost6') || "Generation cost for 1 million text tokens produced by our AI models."
  },
  { 
    label: t('pricing.variable.label7') || "Audio Input Minute", 
    price: "50¢",
    description: t('pricing.variable.cost7') || "Cost per minute of audio processed and transcribed by our AI."
  },
  { 
    label: t('pricing.variable.label8') || "Audio Output Minute", 
    price: "2$",
    description: t('pricing.variable.cost8') || "Cost per minute of high-quality synthetic voice generation."
  },
  { 
    label: t('pricing.variable.label9') || "AI Video Minute", 
    price: "20$",
    description: t('pricing.variable.cost9') || "Cost per minute of custom AI-generated video content."
  },
]

export function VariableCostsSection() {
  const { t } = useLocalization()
  const variableCosts = getVariableCosts(t)

  return (
    <section className="relative w-full py-24 border-t dark:border-white/[0.04] border-black/5 dark:bg-black-paper bg-white-paper bg-[#ffffff] overflow-hidden">
      <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_center,rgba(139,92,246,0.05),transparent_60%)]" />
      <div className="relative z-10 max-w-7xl mx-auto px-6 lg:px-12">
        <div className="text-center mb-16">
          <h2 className="text-3xl md:text-4xl lg:text-5xl font-bold tracking-tighter dark:text-white text-slate-900 mb-6">
            {t('pricing.variable.title.start') || 'Variable Costs &'} <span className="text-transparent bg-clip-text bg-gradient-to-r from-violet-400 to-fuchsia-400">{t('pricing.variable.title.highlight') || 'Additional Credits'}</span>
          </h2>
          <p className="text-lg md:text-xl dark:text-white/50 text-slate-500 max-w-2xl mx-auto font-light">
            {t('pricing.variable.subtitle') || 'Pay only for what you use. Top up credits anytime to scale your partner acquisition outreach.'}
          </p>
        </div>

        {/* Grid of costs */}
        <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-6 mb-24">
          {variableCosts.map((cost, idx) => (
            <div
              key={idx}
              className="rounded-xl dark:neu-base neu-base-light overflow-hidden relative group p-6 md:p-8 flex flex-col justify-center border dark:border-white/[0.06] border-black/5 backdrop-blur-sm transition-all duration-500 hover:-translate-y-2 hover:-translate-x-1 hover:border-violet-500/30 hover:shadow-[10px_10px_0px_rgba(255,255,255,0.05)]"
              style={{ animationDelay: `${idx * 50}ms` }}
            >
              <div className="absolute top-0 right-0 w-32 h-32 bg-gradient-to-br from-violet-500/10 to-fuchsia-500/10 opacity-0 group-hover:opacity-100 transition-opacity duration-500 rounded-full font-inter blur-3xl -translate-y-1/2 translate-x-1/2" />
              <div className="relative z-10 flex flex-col h-full">
                <div className="flex-1">
                  <h3 className="text-sm dark:text-white/70 text-slate-500 font-medium mb-1">{cost.label}</h3>
                  <p className="text-xs dark:text-white/40 text-slate-400 font-light mb-4 line-clamp-2 md:line-clamp-none">{cost.description}</p>
                </div>
                <div className="text-3xl md:text-4xl font-bold dark:text-white text-slate-900 tracking-tight mt-auto">
                  {cost.price}
                </div>
              </div>
            </div>
          ))}
        </div>

        {/* Practical Usage Examples */}
        <div className="mt-20">
          <div className="text-center mb-12">
            <h3 className="text-2xl md:text-3xl font-bold tracking-tighter dark:text-white text-slate-900 mb-4">
              {t('pricing.variable.examples.title') || 'Practical Usage Examples'}
            </h3>
            <p className="text-md dark:text-white/50 text-slate-500 max-w-2xl mx-auto font-light">
              {t('pricing.variable.examples.subtitle') || 'See how our credit system works in real-world scenarios.'}
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            {/* Example 1 */}
            <div className="rounded-xl dark:neu-base neu-base-light p-8 border dark:border-white/[0.06] border-black/5 backdrop-blur-sm transition-all duration-500 hover:-translate-y-2 hover:-translate-x-1 hover:border-violet-500/30 hover:shadow-[10px_10px_0px_rgba(255,255,255,0.05)]">
              <h4 className="text-xl font-bold dark:text-white text-slate-900 mb-4 flex items-center gap-3">
                <span className="flex items-center justify-center w-8 h-8 rounded-full font-inter font-bold bg-violet-500/10 text-violet-600 dark:bg-violet-500/20 dark:text-violet-400 text-sm font-bold shadow-inner">1</span>
                {t('pricing.variable.ex1.title') || 'Recruitment Campaign'}
              </h4>
              <p className="dark:text-white/70 text-slate-500 mb-6 text-sm font-light">
                {t('pricing.variable.ex1.desc') || 'Generate 1,000 highly targeted partner profiles using AI and enrich them with deep research.'}
              </p>
              <ul className="space-y-3 mb-6">
                <li className="flex justify-between items-center text-sm">
                  <span className="dark:text-white/60 text-slate-500">{t('pricing.variable.ex1.item1') || '1,000 AI-Generated Partner Profiles'}</span>
                  <span className="dark:text-white text-slate-900 font-medium">$500.00</span>
                </li>
                <li className="flex justify-between items-center text-sm">
                  <span className="dark:text-white/60 text-slate-500">{t('pricing.variable.ex1.item2') || '2,000 API Calls / Deep Research'}</span>
                  <span className="dark:text-white text-slate-900 font-medium">$20.00</span>
                </li>
              </ul>
              <div className="pt-4 border-t dark:border-white/[0.06] border-black/5 flex justify-between items-center">
                <span className="font-bold dark:text-white text-slate-900">{t('pricing.variable.totalCost') || 'Total Estimated Cost'}</span>
                <span className="text-xl font-bold text-violet-600 dark:text-violet-400">$520.00</span>
              </div>
            </div>

            {/* Example 2 */}
            <div className="rounded-xl dark:neu-base neu-base-light p-8 border dark:border-white/[0.06] border-black/5 backdrop-blur-sm transition-all duration-500 hover:-translate-y-2 hover:-translate-x-1 hover:border-orange-500/30 hover:shadow-[10px_10px_0px_rgba(255,255,255,0.05)]">
              <h4 className="text-xl font-bold dark:text-white text-slate-900 mb-4 flex items-center gap-3">
                <span className="flex items-center justify-center w-8 h-8 rounded-full font-inter font-bold bg-orange-500/10 text-orange-600 dark:bg-orange-500/20 dark:text-orange-400 text-sm font-bold shadow-inner">2</span>
                {t('pricing.variable.ex2.title') || 'Closing and Signing Partners'}
              </h4>
              <p className="dark:text-white/70 text-slate-500 mb-6 text-sm font-light">
                {t('pricing.variable.ex2.desc') || 'Outsource 50 prospecting meetings and successfully sign 10 new distributors.'}
              </p>
              <ul className="space-y-3 mb-6">
                <li className="flex justify-between items-center text-sm">
                  <span className="dark:text-white/60 text-slate-500">{t('pricing.variable.ex2.item1') || '50 Outsourced Partner Meetings'}</span>
                  <span className="dark:text-white text-slate-900 font-medium">$1,000.00</span>
                </li>
                <li className="flex justify-between items-center text-sm">
                  <span className="dark:text-white/60 text-slate-500">{t('pricing.variable.ex2.item2') || '10 Signed Partners (Bonus)'}</span>
                  <span className="dark:text-white text-slate-900 font-medium">$100.00</span>
                </li>
              </ul>
              <div className="pt-4 border-t dark:border-white/[0.06] border-black/5 flex justify-between items-center">
                <span className="font-bold dark:text-white text-slate-900">{t('pricing.variable.totalCost') || 'Total Estimated Cost'}</span>
                <span className="text-xl font-bold text-orange-600 dark:text-orange-400">$1,100.00</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  )
}
