"use client"

import React, { useState, useEffect } from "react"
import { useRouter } from "next/navigation"
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from "@/app/components/ui/dialog"
import { Button } from "@/app/components/ui/button"
import { Input } from "@/app/components/ui/input"
import { Textarea } from "@/app/components/ui/textarea"
import { Label } from "@/app/components/ui/label"
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/app/components/ui/select"
import { DatePicker } from "@/app/components/ui/date-picker"
import { format, addDays } from "date-fns"
import { Task, TASK_TYPES, JOURNEY_STAGES, TASK_STATUSES } from "../types"
import { useTasks } from "../context/TasksContext"

interface AddTaskDialogProps {
  isOpen: boolean
  onOpenChange: (open: boolean) => void
  leadId: string
}

export function AddTaskDialog({ isOpen, onOpenChange, leadId }: AddTaskDialogProps) {
  const { createTask } = useTasks()
  const router = useRouter()
  
  // Form state
  const [title, setTitle] = useState("")
  const [description, setDescription] = useState("")
  const [type, setType] = useState<Task["type"]>("meeting")
  const [stage, setStage] = useState<Task["stage"]>("awareness")
  const [status, setStatus] = useState<Task["status"]>("pending")
  const [scheduledDate, setScheduledDate] = useState<Date>(new Date())
  const [amount, setAmount] = useState<string>("")
  const [notes, setNotes] = useState<string>("")
  const [submitting, setSubmitting] = useState(false)
  
  // Get pre-selected stage when dialog opens
  useEffect(() => {
    if (isOpen) {
      const selectedStage = sessionStorage.getItem('selectedStage') as Task["stage"] | null
      if (selectedStage) {
        setStage(selectedStage)
        // Clear after using
        sessionStorage.removeItem('selectedStage')
      }
    }
  }, [isOpen])
  
  // Reset form
  const resetForm = () => {
    setTitle("")
    setDescription("")
    setType("meeting")
    setStage("awareness")
    setStatus("pending")
    setScheduledDate(new Date())
    setAmount("")
    setNotes("")
  }
  
  // Handle form submission
  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    setSubmitting(true)
    
    try {
      // Create task object matching Task interface structure
      const taskData: Omit<Task, "id" | "created_at"> = {
        serial_id: "", // Will be generated by backend
        lead_id: leadId,
        title,
        description: description || "",
        type,
        stage,
        status,
        scheduled_date: scheduledDate.toISOString(),
        priority: 1, // Default priority
        // Optional fields
        ...(stage !== "awareness" && amount ? { amount: Number(amount) } : {}),
        ...(notes ? { notes } : {}),
      }
      
      await createTask(taskData)
      
      // Close dialog and reset form
      onOpenChange(false)
      resetForm()
    } catch (error) {
      console.error("Failed to create task:", error)
      // No necesitamos mostrar el toast aquí ya que el TasksContext ya lo maneja
    } finally {
      setSubmitting(false)
    }
  }
  
  return (
    <Dialog open={isOpen} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-[500px]">
        <DialogHeader>
          <DialogTitle>Add Task</DialogTitle>
        </DialogHeader>
        
        <form onSubmit={handleSubmit}>
          <div className="grid gap-4 py-4">
            <div className="grid grid-cols-1 gap-2">
              <Label htmlFor="title" className="text-sm font-medium">Title <span className="text-red-500">*</span></Label>
              <Input
                id="title"
                value={title}
                onChange={(e) => setTitle(e.target.value)}
                className="h-12"
                placeholder="Enter task title"
                required
              />
            </div>
            
            <div className="grid grid-cols-1 gap-2">
              <Label htmlFor="description" className="text-sm font-medium">Description</Label>
              <Textarea
                id="description"
                value={description}
                onChange={(e) => setDescription(e.target.value)}
                className="min-h-[80px]"
                placeholder="Enter task description"
              />
            </div>
            
            <div className="grid grid-cols-2 gap-4">
              <div className="grid grid-cols-1 gap-2">
                <Label htmlFor="type" className="text-sm font-medium">Type</Label>
                <Select
                  value={type}
                  onValueChange={(value) => setType(value as Task["type"])}
                >
                  <SelectTrigger id="type" className="h-12">
                    <SelectValue placeholder="Select type" />
                  </SelectTrigger>
                  <SelectContent>
                    {TASK_TYPES.map((type) => (
                      <SelectItem key={type.id} value={type.id}>
                        <div className="flex items-center gap-2">
                          <span>{type.emoji}</span>
                          <span>{type.name}</span>
                        </div>
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
              
              {stage !== "awareness" && (
                <div className="grid grid-cols-1 gap-2">
                  <Label htmlFor="amount" className="text-sm font-medium">Amount ($)</Label>
                  <Input
                    id="amount"
                    type="number"
                    value={amount}
                    onChange={(e) => setAmount(e.target.value)}
                    placeholder="0.00"
                    step="0.01"
                    min="0"
                    className="h-12"
                  />
                </div>
              )}
            </div>
            
            <div className="grid grid-cols-2 gap-4">
              <div className="grid grid-cols-1 gap-2">
                <Label htmlFor="status" className="text-sm font-medium">Status</Label>
                <Select
                  value={status}
                  onValueChange={(value) => setStatus(value as Task["status"])}
                >
                  <SelectTrigger id="status" className="h-12">
                    <SelectValue placeholder="Select status" />
                  </SelectTrigger>
                  <SelectContent>
                    {TASK_STATUSES.map((status) => (
                      <SelectItem key={status.id} value={status.id}>{status.name}</SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
              
              <div className="grid grid-cols-1 gap-2">
                <Label className="text-sm font-medium">Scheduled Date</Label>
                <div className="relative z-[1000000]">
                  <DatePicker 
                    date={scheduledDate}
                    setDate={setScheduledDate}
                    position="top"
                    className="w-full"
                    mode="task"
                    showTimePicker={true}
                    timeFormat="12h"
                  />
                </div>
              </div>
            </div>
            
            <div className="grid grid-cols-1 gap-2">
              <Label htmlFor="notes" className="text-sm font-medium">Notes</Label>
              <Textarea
                id="notes"
                value={notes}
                onChange={(e) => setNotes(e.target.value)}
                className="min-h-[80px]"
                placeholder="Enter additional notes"
              />
            </div>
          </div>
          
          <DialogFooter>
            <Button 
              type="button" 
              variant="outline" 
              onClick={() => {
                resetForm()
                onOpenChange(false)
              }}
              disabled={submitting}
            >
              Cancel
            </Button>
            <Button type="submit" disabled={submitting}>
              {submitting ? "Adding..." : "Add Task"}
            </Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  )
} 