import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type SupportedLocale = 'en' | 'es' | 'fr' | 'de' | 'ja';

interface LocalizationContextType {
  locale: SupportedLocale;
  setLocale: (locale: SupportedLocale) => void;
  // helper to get localized strings/assets
  t: (key: string) => string; 
  getAsset: (key: string) => string;
}

const defaultLocale: SupportedLocale = 'en';

const LocalizationContext = createContext<LocalizationContextType | undefined>(undefined);

// In a real app, this would be loaded dynamically or pre-compiled
const translations: Record<SupportedLocale, Record<string, string>> = {
  en: {
    'common.soon': 'Soon',
    'features.title.start': 'Everything you need,',
    'features.title.highlight': 'stage by stage',
    'features.subtitle': 'A complete suite of tools integrated into one seamless platform from first touch to closed won.',
    
    'features.stages.find.title': 'Find',
    'features.stages.find.f1': 'TAM sourcing',
    'features.stages.find.f2': 'Contact enrichment',
    'features.stages.find.f3': 'Company enrichment',
    'features.stages.find.f4': 'Intent signals',
    'features.stages.find.f5': 'Lead scoring',
    
    'features.stages.contact.title': 'Contact',
    'features.stages.contact.f1': 'Domain & inbox purchase',
    'features.stages.contact.f2': 'Inbox warming',
    'features.stages.contact.f3': 'Sequencing',
    'features.stages.contact.f4': 'Dialer',
    'features.stages.contact.f5': 'Scheduler',
    
    'features.stages.sell.title': 'Sell',
    'features.stages.sell.f1': 'Ad management',
    'features.stages.sell.f2': 'Inbound Automation',
    'features.stages.sell.f3': 'SEO & Content automation',
    'features.stages.sell.f4': 'Smart email composer',
    'features.stages.sell.f5': 'Smart task logging',
    
    'features.stages.manage.title': 'Manage',
    'features.stages.manage.f1': 'CRM',
    'features.stages.manage.f2': 'Ask AI Copilot',
    'features.stages.manage.f3': 'Reporting',
    'features.stages.manage.f4': 'Workflows',
    'features.stages.manage.f5': 'Integrations',
    
    'features.sections.find.badge': 'Find',
    'features.sections.find.title': 'Zero in on the buyers who matter',
    'features.sections.find.subtitle': 'Build, refine, and activate your ideal lead list directly within the platform. We automatically dedupe and map new contacts to accounts so your data is always clean and actionable.',
    'features.sections.find.mockup.title': 'Target Accounts',
    'features.sections.find.mockup.subtitle': 'Finding matches...',
    'features.sections.find.mockup.auto': 'Auto-find',
    'features.sections.find.mockup.enriched': 'Enriched',
    'features.sections.find.mockup.pending': 'Pending',
    'features.sections.find.mockup.dataFound': 'Data Found',
    'features.sections.find.mockup.leads': 'Leads',
    
    'features.sections.contact.badge': 'Contact',
    'features.sections.contact.title': 'Build pipeline without the patchwork',
    'features.sections.contact.subtitle': 'Dialer and sequences built directly into your CRM. Manage your entire outreach without ever switching tabs.',
    'features.sections.contact.mockup.sequences': 'Sequences',
    'features.sections.contact.mockup.assistant': 'AI Assistant',
    'features.sections.contact.mockup.drafting': 'Drafting response...',
    'features.sections.contact.mockup.send': 'Send Sequence',
    'features.sections.contact.mockup.opened': 'Email Opened',
    'features.sections.contact.mockup.openedBy': 'Just now by John Doe',
    
    'features.sections.sell.badge': 'Sell',
    'features.sections.sell.title': 'Turn traffic into conversions',
    'features.sections.sell.subtitle': 'Use natively built AI tools to optimize ad campaigns, manage budgets, and capture high-intent leads on autopilot, keeping your inbound pipeline full.',
    'features.sections.sell.mockup.adSpend': 'Ad Spend',
    'features.sections.sell.mockup.costPerLead': 'Cost / Lead',
    'features.sections.sell.mockup.activeCampaigns': 'Active Campaigns',
    'features.sections.sell.mockup.aiOptimizing': 'AI Optimizing',
    'features.sections.sell.mockup.active': 'Active',
    'features.sections.sell.mockup.learning': 'Learning',
    'features.sections.sell.mockup.c1': 'Q4 Retargeting',
    'features.sections.sell.mockup.c2': 'Lookalike Top Tier',
    'features.sections.sell.mockup.c3': 'Cold Outbound Search',
    'features.sections.sell.mockup.newLead': 'New Lead',
    'features.sections.sell.mockup.viaLookalike': 'via Lookalike Tier',
    
    'features.sections.manage.badge': 'Manage',
    'features.sections.manage.title': 'Operate from a single source of truth',
    'features.sections.manage.subtitle': 'Your pipeline manages itself with automated activity logging and stage gating. You can trust your forecast because it\'s based on real activity, not manual updates.',
    'features.sections.manage.mockup.pipelineValue': 'Pipeline Value',
    'features.sections.manage.mockup.projected': 'Projected Revenue',
    'features.sections.manage.mockup.insight': 'Copilot Insight',
    'features.sections.manage.mockup.insightText': 'Acme Corp deal is stalling. Consider sending the ROI calculator to the CFO. I can draft this email for you.',
    'features.sections.manage.mockup.draftEmail': 'Draft Email',
    'features.sections.manage.mockup.dismiss': 'Dismiss',
    'features.sections.manage.mockup.stage1': 'Lead',
    'features.sections.manage.mockup.stage2': 'Meeting',
    'features.sections.manage.mockup.stage3': 'Proposal',
    'features.sections.manage.mockup.stage4': 'Negotiation',
    'features.sections.manage.mockup.stage5': 'Closed',
    
    'pricing.title.start': 'Simple',
    'pricing.title.highlight': 'pricing',
    'pricing.subtitle': 'Choose the plan that fits your needs. Scale as you grow.',
    'pricing.mostPopular': 'Most Popular',
    'pricing.period': '/month',
    'pricing.free.title': 'Free',
    'pricing.free.desc': 'Pay just for results and scale on demand',
    'pricing.free.f1': 'Up to 5 social networks',
    'pricing.free.f2': 'Web channel',
    'pricing.free.f3': 'Bring your own Twilio and email',
    'pricing.free.f4': 'Community Access',
    'pricing.free.f5': 'Standard Support',
    'pricing.free.f6': '30 Credits',
    'pricing.free.cta': 'Start Now',
    
    'pricing.startup.title': 'Startup',
    'pricing.startup.desc': 'All Included',
    'pricing.startup.f1': 'Unlimited social networks',
    'pricing.startup.f2': 'Personalized email account',
    'pricing.startup.f3': 'WhatsApp account',
    'pricing.startup.f4': 'Phone number account',
    'pricing.startup.f5': 'API access',
    'pricing.startup.f6': 'Priority support',
    'pricing.startup.f7': '100 Credits',
    'pricing.startup.cta': 'Purchase',
    
    'pricing.gtm.title': 'GTM',
    'pricing.gtm.desc': 'Performance sales and marketing services',
    'pricing.gtm.prefix': 'from ',
    'pricing.gtm.f1': 'Dedicated GTM Engineer',
    'pricing.gtm.f2': 'Web analytics tracking',
    'pricing.gtm.f3': 'AD allocation',
    'pricing.gtm.f4': 'Advanced Integrations',
    'pricing.gtm.f5': '24/7 priority support',
    'pricing.gtm.f6': '500 Credits',
    'pricing.gtm.cta': 'Contact Us',
    
    'openclaw.title.start': 'Your team of',
    'openclaw.title.highlight': 'virtual employees',
    'openclaw.subtitle': 'Deploy specialized AI agents to handle complex tasks across strategy, campaigns, SEO, and operations. Like having an entire department working 24/7.',
    'openclaw.agent.strategy.name': 'Strategy Agent',
    'openclaw.agent.strategy.status': 'Analyze market fit',
    'openclaw.agent.strategy.prompt': 'Analyze our current product-market fit and identify the biggest gaps we should address.',
    'openclaw.agent.growth.name': 'Growth Agent',
    'openclaw.agent.growth.status': 'Generating Document...',
    'openclaw.agent.growth.task': 'Go-to-market strategy',
    'openclaw.agent.data.name': 'Data Agent',
    'openclaw.agent.data.task': 'Define ICP & Enrich Leads',
    'openclaw.agent.data.status': 'Processing',
    'openclaw.agent.scraping.name': 'Scraping Agent',
    'openclaw.agent.scraping.status': 'Gathering Intelligence...',
    'openclaw.agent.scraping.task': 'SEO strategy & Competitors',
    'openclaw.agent.scraping.badge': 'Extracted',
    'openclaw.agent.marketing.name': 'Marketing Agent',
    'openclaw.agent.marketing.task': 'Ad copy variants',
    'openclaw.agent.marketing.prompt': 'Write 5 ad copy variants for a Facebook ad...',
    
    'support.title': 'With the support of',
    
    'mockupslider.tab.crm': 'CRM',
    'mockupslider.tab.control': 'Control Center',
    'mockupslider.tab.reports': 'Reports',
    'mockupslider.tab.inbox': 'Omni Inbox',
    'mockupslider.tab.agents': 'AI Agents',
    'mockupslider.tab.goals': 'AI Goals',
    
    'mockupslider.crm.newLeads': 'New Leads',
    'mockupslider.crm.engaged': 'Engaged by AI',
    'mockupslider.crm.meeting': 'Meeting Booked',
    'mockupslider.crm.active': 'Active',
    'mockupslider.crm.pending': 'Pending',
    'mockupslider.crm.meetingBooked': 'Meeting Booked',
    'mockupslider.crm.agentClosed': 'AI Agent closed the deal automatically',
    'mockupslider.crm.agentTyping': 'Agent typing...',
    
    'mockupslider.control.inProgress': 'In Progress',
    'mockupslider.control.timeline': 'Timeline',
    'mockupslider.control.details': 'Details',
    'mockupslider.control.writeUpdate': 'Write an update or comment...',
    'mockupslider.control.postUpdate': 'Post Update',
    'mockupslider.control.time1': 'Just now',
    'mockupslider.control.msg1': 'I have successfully analyzed the data chunk and updated the relevant database tables. The synchronization is now 65% complete.',
    'mockupslider.control.time2': '2 hours ago',
    'mockupslider.control.msg2': 'Can you provide a summary of the anomalies found so far?',
    'mockupslider.control.time3': '3 hours ago',
    'mockupslider.control.msg3': 'Initial data extraction completed. Found 124 records with missing identifiers.',
    'mockupslider.control.taskTitle': 'Data Sync & Analysis',
    'mockupslider.control.assignedTo': 'Task assigned to AI Agent',
    'mockupslider.control.taskDesc': 'Synchronize 50k records from the legacy database and perform anomaly detection. Create a detailed report for any missing identifiers or formatting issues.',
    'mockupslider.control.badgeUpdate': 'Task Update',
    'mockupslider.control.badgeUpdateDesc': 'AI Agent analyzed 50k records',
    'mockupslider.control.badgeAnomaly': 'Anomaly Detected',
    
    'mockupslider.dashboard.title': 'Analytics Reports',
    'mockupslider.dashboard.period': 'Last 30 Days',
    'mockupslider.dashboard.stat1': 'Total Revenue',
    'mockupslider.dashboard.stat2': 'Active Users',
    'mockupslider.dashboard.stat3': 'Conversion Rate',
    'mockupslider.dashboard.stat4': 'Avg Session',
    'mockupslider.dashboard.chartTitle': 'Revenue Overview',
    
    'mockupslider.chat.search': 'Search messages...',
    'mockupslider.chat.team': 'Sales Team',
    'mockupslider.chat.msg1': 'Great job on the new campaign!',
    'mockupslider.chat.msg2': 'I\'ve drafted 5 new emails.',
    'mockupslider.chat.support': 'Support',
    'mockupslider.chat.msg3': 'Ticket #1042 resolved.',
    'mockupslider.chat.yesterday': 'Yesterday',
    'mockupslider.chat.marketing': 'Marketing',
    'mockupslider.chat.msg4': 'Assets are ready for review.',
    'mockupslider.chat.online': '4 members online',
    'mockupslider.chat.today': 'Today',
    'mockupslider.chat.bubble1': 'Hey team, how\'s the new outreach campaign performing?',
    'mockupslider.chat.bubble2': 'I\'ve analyzed the initial data. Open rates are up 24% compared to last week. I\'ve also automatically followed up with 45 engaged leads.',
    'mockupslider.chat.bubble3': 'That\'s amazing! Can you generate a report for the weekly meeting?',
    'mockupslider.chat.bubble4': 'Absolutely. I\'m compiling the metrics now.',
    'mockupslider.chat.reportName': 'campaign_report_v1.pdf',
    'mockupslider.chat.reportSize': '1.2 MB • Ready',
    'mockupslider.chat.placeholder': 'Type a message or ask AI...',
    'mockupslider.chat.autoReply': 'Auto-Reply Sent',
    'mockupslider.chat.autoReplyDesc': 'AI handled 45 inquiries',
    'mockupslider.chat.leadQualified': 'Lead Qualified',
    'mockupslider.chat.leadQualifiedDesc': 'Transferred to Sales',
    
    'mockupslider.agents.new': 'New Makina',
    'mockupslider.agents.instance1': 'Instance 1',
    'mockupslider.agents.instance2': 'Instance 2',
    'mockupslider.agents.running': 'Running Task...',
    'mockupslider.agents.agentLog': 'Agent Log',
    'mockupslider.agents.log1': '[10:42:01] Navigating to target URL...',
    'mockupslider.agents.log2': '[10:42:03] Page loaded successfully',
    'mockupslider.agents.log3': '[10:42:05] Scanning DOM elements...',
    'mockupslider.agents.log4': '[10:42:06] Found target form, analyzing fields',
    'mockupslider.agents.log5a': 'Executing action: FILL_FORM',
    'mockupslider.agents.log5b': 'Extracted 5 fields',
    'mockupslider.agents.log5c': 'Injecting data...',
    'mockupslider.agents.log6': '[10:42:08] Form filled, awaiting confirmation',
    'mockupslider.agents.instruction': 'Send instruction...',
    'mockupslider.agents.deployed': 'Instance Deployed',
    'mockupslider.agents.deployedDesc': 'Running form automation',
    'mockupslider.agents.completed': 'Action Completed',
    'mockupslider.agents.completedDesc': '5 fields extracted & injected',
    
    'mockupslider.goals.tab1': 'All Requirements',
    'mockupslider.goals.tab2': 'Pending',
    'mockupslider.goals.tab3': 'Completed',
    'mockupslider.goals.newGoal': 'New Goal',
    'mockupslider.goals.type.feature': 'Feature',
    'mockupslider.goals.type.optimization': 'Optimization',
    'mockupslider.goals.type.bug': 'Bug',
    'mockupslider.goals.status.inProgress': 'In Progress',
    'mockupslider.goals.status.pending': 'Pending',
    'mockupslider.goals.status.completed': 'Completed',
    'mockupslider.goals.priority.critical': 'Critical',
    'mockupslider.goals.priority.high': 'High',
    'mockupslider.goals.priority.medium': 'Medium',
    'mockupslider.goals.g1.title': 'Automate Outreach Setup',
    'mockupslider.goals.g2.title': 'Optimize Landing Page Speed',
    'mockupslider.goals.g3.title': 'Fix API Rate Limiting',
    'mockupslider.goals.g4.title': 'Implement Stripe Billing',
    'mockupslider.goals.progress': 'Progress',
    'mockupslider.goals.goalAchieved': 'Goal Achieved',
    'mockupslider.goals.goalAchievedDesc': 'API Rate Limiting fixed',
    'mockupslider.goals.autoPrioritization': 'Auto-prioritization',
    'mockupslider.goals.autoPrioritizationDesc': 'Stripe Billing moved to High',
    
    'auth.welcomeBack': 'Makinari is the Revenue Operations Platform with Agents that actually perform tasks for you',
    'auth.welcomeAboard': 'Welcome aboard',
    'auth.signInDesc': 'Sign in to manage your AI sales agents',
    'auth.signUpDesc': 'Get started with AI-powered sales automation',
    'auth.backedBy': 'Backed by',
    'auth.chip.gtm': 'GTM',
    'auth.chip.crm': 'CRM',
    'auth.chip.employees': 'Employees',
    'auth.chip.openSource': 'Open Source',
    'auth.email': 'Email address',
    'auth.emailPlaceholder': 'name@example.com',
    'auth.password': 'Password',
    'auth.passwordPlaceholder': 'Enter your password',
    'auth.forgotPassword': 'Forgot password?',
    'auth.signInBtn': 'Sign In',
    'auth.signUpBtn': 'Create account',
    'auth.orContinue': 'OR CONTINUE WITH',
    'auth.whatsappBtn': 'Use Makinari on WhatsApp',
    'auth.noAccount': 'Don\'t have an account?',
    'auth.signUpLink': 'Sign up',
    'auth.hasAccount': 'Already have an account?',
    'auth.signInLink': 'Sign in',
    'auth.firstName': 'First name',
    'auth.lastName': 'Last name',
    'auth.company': 'Company',
    'auth.companyOptional': 'Company (optional)',
    'auth.creating': 'Creating account...',
    'auth.sendReset': 'Send reset instructions',
    'auth.backToSignIn': 'Back to sign in',

    'landing.scale.title.start': 'Everything you need to',
    'landing.scale.title.highlight': 'scale',
    'landing.scale.subtitle': 'A complete suite of tools integrated into one seamless platform. No more duct-taping disjointed software.',
    'landing.outbound.badge': 'Massive Scale',
    'landing.outbound.title': 'Outbound ready system',
    'landing.outbound.subtitle': 'Launch campaigns in minutes. Reach thousands of prospects across multiple channels with personalized messages at scale, without hitting spam limits.',
    'landing.outbound.deliveryRate': 'Delivery Rate',
    'landing.omnichannel.badge': 'Omnichannel',
    'landing.omnichannel.title': 'Channel automation',
    'landing.omnichannel.subtitle': 'Connect Email, WhatsApp, LinkedIn, and more. Orchestrate all communications in one place.',
    'landing.developer.title': 'Open source MCP',
    'landing.developer.subtitle': 'Built for builders. Host on your own infrastructure with open-source capabilities.',
    'landing.seo.badge': 'Growth Engine',
    'landing.seo.title': 'SEO & sites specialist',
    'landing.seo.subtitle': 'Optimize your web presence automatically. Generate SEO-perfected content, track rankings in real-time, and improve site performance continuously.',
    'landing.content.title.start': 'Automatic content',
    'landing.content.title.highlight': 'generation',
    'landing.content.subtitle': 'Create highly engaging videos, social posts, and personalized emails on autopilot. Consistent, on-brand content for every channel.',

    'footer.product': 'Product',
    'footer.product.features': 'Features',
    'footer.product.agents': 'AI Agents',
    'footer.product.integrations': 'Integrations',
    'footer.product.pricing': 'Pricing',
    'footer.product.changelog': 'Changelog',
    'footer.resources': 'Resources',
    'footer.resources.docs': 'Documentation',
    'footer.resources.api': 'API Reference',
    'footer.resources.community': 'Community',
    'footer.resources.blog': 'Blog',
    'footer.resources.guides': 'Guides',
    'footer.company': 'Company',
    'footer.company.about': 'About Us',
    'footer.company.careers': 'Careers',
    'footer.company.contact': 'Contact',
    'footer.company.privacy': 'Privacy Policy',
    'footer.company.terms': 'Terms of Service',
    'footer.allSystemsOperational': 'All systems operational',
    'footer.rightsReserved': 'Makinari Inc. All rights reserved.',
    'footer.tagline': 'The Revenue Operations Platform with AI agents that actually perform tasks for you. Scale your outbound, content, and growth automatically.',
    'language.en': 'English',
    'language.es': 'Spanish',
    'language.fr': 'French',
    'language.de': 'German',
    'language.ja': 'Japanese',
    'virtual.badge': 'RevOps',
    'virtual.title': 'Revenue Operations Platform',
    'virtual.title.start': 'Revenue ',
    'virtual.title.highlight': 'Operations Platform',
    'virtual.subtitle': 'Automate your entire sales process with AI agents that work 24/7. From lead generation to closing deals, our virtual employees handle it all.',
    'virtual.kanban.newLeads': 'New Leads',
    'virtual.kanban.engaged': 'Engaged by AI',
    'virtual.kanban.meeting': 'Meeting Booked',
    'virtual.kanban.active': 'Active',
    'virtual.kanban.pending': 'Pending',
    'virtual.badge.title': 'Meeting Booked',
    'virtual.badge.subtitle': 'AI Agent closed the deal',
    'virtual.badge.typing': 'Agent typing...',
  },
  es: {
    'common.soon': 'Pronto',
    'features.title.start': 'Todo lo que necesitas,',
    'features.title.highlight': 'etapa por etapa',
    'features.subtitle': 'Un conjunto completo de herramientas integradas en una plataforma perfecta, desde el primer contacto hasta el cierre de la venta.',
    
    'features.stages.find.title': 'Encontrar',
    'features.stages.find.f1': 'Búsqueda de mercado total',
    'features.stages.find.f2': 'Enriquecimiento de contactos',
    'features.stages.find.f3': 'Enriquecimiento de empresas',
    'features.stages.find.f4': 'Señales de intención',
    'features.stages.find.f5': 'Calificación de prospectos',
    
    'features.stages.contact.title': 'Contactar',
    'features.stages.contact.f1': 'Compra de dominios y correos',
    'features.stages.contact.f2': 'Calentamiento de bandejas',
    'features.stages.contact.f3': 'Secuencias automáticas',
    'features.stages.contact.f4': 'Marcador automático',
    'features.stages.contact.f5': 'Programador de citas',
    
    'features.stages.sell.title': 'Vender',
    'features.stages.sell.f1': 'Gestión de anuncios',
    'features.stages.sell.f2': 'Automatización Inbound',
    'features.stages.sell.f3': 'Automatización de SEO y contenido',
    'features.stages.sell.f4': 'Compositor inteligente de emails',
    'features.stages.sell.f5': 'Registro inteligente de tareas',
    
    'features.stages.manage.title': 'Gestionar',
    'features.stages.manage.f1': 'CRM',
    'features.stages.manage.f2': 'Pregúntale a Copilot IA',
    'features.stages.manage.f3': 'Reportes',
    'features.stages.manage.f4': 'Flujos de trabajo',
    'features.stages.manage.f5': 'Integraciones',
    
    'features.sections.find.badge': 'Encontrar',
    'features.sections.find.title': 'Concéntrate en los compradores que importan',
    'features.sections.find.subtitle': 'Construye, refina y activa tu lista de leads ideal directamente en la plataforma. Eliminamos duplicados automáticamente y mapeamos nuevos contactos a cuentas para que tus datos siempre estén limpios y procesables.',
    'features.sections.find.mockup.title': 'Cuentas Objetivo',
    'features.sections.find.mockup.subtitle': 'Buscando coincidencias...',
    'features.sections.find.mockup.auto': 'Búsqueda automática',
    'features.sections.find.mockup.enriched': 'Enriquecido',
    'features.sections.find.mockup.pending': 'Pendiente',
    'features.sections.find.mockup.dataFound': 'Datos Encontrados',
    'features.sections.find.mockup.leads': 'Prospectos',
    
    'features.sections.contact.badge': 'Contactar',
    'features.sections.contact.title': 'Construye pipeline sin los parches',
    'features.sections.contact.subtitle': 'Marcador automático y secuencias incorporados directamente en tu CRM. Gestiona todo tu alcance sin tener que cambiar de pestaña.',
    'features.sections.contact.mockup.sequences': 'Secuencias',
    'features.sections.contact.mockup.assistant': 'Asistente IA',
    'features.sections.contact.mockup.drafting': 'Redactando respuesta...',
    'features.sections.contact.mockup.send': 'Enviar Secuencia',
    'features.sections.contact.mockup.opened': 'Correo Abierto',
    'features.sections.contact.mockup.openedBy': 'Hace un momento por John Doe',
    
    'features.sections.sell.badge': 'Vender',
    'features.sections.sell.title': 'Convierte el tráfico en conversiones',
    'features.sections.sell.subtitle': 'Usa herramientas de IA integradas para optimizar campañas de anuncios, gestionar presupuestos y capturar leads con alta intención en piloto automático, manteniendo tu embudo inbound lleno.',
    'features.sections.sell.mockup.adSpend': 'Gasto Publicitario',
    'features.sections.sell.mockup.costPerLead': 'Costo / Lead',
    'features.sections.sell.mockup.activeCampaigns': 'Campañas Activas',
    'features.sections.sell.mockup.aiOptimizing': 'IA Optimizando',
    'features.sections.sell.mockup.active': 'Activa',
    'features.sections.sell.mockup.learning': 'Aprendiendo',
    'features.sections.sell.mockup.c1': 'Retargeting Q4',
    'features.sections.sell.mockup.c2': 'Público Similar Top',
    'features.sections.sell.mockup.c3': 'Búsqueda Outbound Fría',
    'features.sections.sell.mockup.newLead': 'Nuevo Lead',
    'features.sections.sell.mockup.viaLookalike': 'vía Público Similar',
    
    'features.sections.manage.badge': 'Gestionar',
    'features.sections.manage.title': 'Opera desde una única fuente de verdad',
    'features.sections.manage.subtitle': 'Tu pipeline se gestiona a sí mismo con registro automático de actividad y control de etapas. Puedes confiar en tu pronóstico porque se basa en actividad real, no en actualizaciones manuales.',
    'features.sections.manage.mockup.pipelineValue': 'Valor del Pipeline',
    'features.sections.manage.mockup.projected': 'Ingresos Proyectados',
    'features.sections.manage.mockup.insight': 'Insight del Copilot',
    'features.sections.manage.mockup.insightText': 'El trato con Acme Corp está estancado. Considera enviar la calculadora de ROI al Director Financiero. Puedo redactar este correo por ti.',
    'features.sections.manage.mockup.draftEmail': 'Redactar Correo',
    'features.sections.manage.mockup.dismiss': 'Descartar',
    'features.sections.manage.mockup.stage1': 'Lead',
    'features.sections.manage.mockup.stage2': 'Reunión',
    'features.sections.manage.mockup.stage3': 'Propuesta',
    'features.sections.manage.mockup.stage4': 'Negociación',
    'features.sections.manage.mockup.stage5': 'Cierre',
    
    'pricing.title.start': 'Precios',
    'pricing.title.highlight': 'simples',
    'pricing.subtitle': 'Elige el plan que se adapte a tus necesidades. Escala a medida que creces.',
    'pricing.mostPopular': 'Más Popular',
    'pricing.period': '/mes',
    'pricing.free.title': 'Gratis',
    'pricing.free.desc': 'Paga solo por resultados y escala a demanda',
    'pricing.free.f1': 'Hasta 5 redes sociales',
    'pricing.free.f2': 'Canal web',
    'pricing.free.f3': 'Usa tu propio Twilio y correo',
    'pricing.free.f4': 'Acceso a la comunidad',
    'pricing.free.f5': 'Soporte estándar',
    'pricing.free.f6': '30 Créditos',
    'pricing.free.cta': 'Empezar ahora',
    
    'pricing.startup.title': 'Startup',
    'pricing.startup.desc': 'Todo Incluido',
    'pricing.startup.f1': 'Redes sociales ilimitadas',
    'pricing.startup.f2': 'Cuenta de correo personalizada',
    'pricing.startup.f3': 'Cuenta de WhatsApp',
    'pricing.startup.f4': 'Cuenta de número telefónico',
    'pricing.startup.f5': 'Acceso API',
    'pricing.startup.f6': 'Soporte prioritario',
    'pricing.startup.f7': '100 Créditos',
    'pricing.startup.cta': 'Comprar',
    
    'pricing.gtm.title': 'GTM',
    'pricing.gtm.desc': 'Servicios de ventas y marketing de alto rendimiento',
    'pricing.gtm.prefix': 'desde ',
    'pricing.gtm.f1': 'Ingeniero GTM dedicado',
    'pricing.gtm.f2': 'Seguimiento de analítica web',
    'pricing.gtm.f3': 'Asignación de anuncios',
    'pricing.gtm.f4': 'Integraciones avanzadas',
    'pricing.gtm.f5': 'Soporte prioritario 24/7',
    'pricing.gtm.f6': '500 Créditos',
    'pricing.gtm.cta': 'Contáctanos',
    
    'openclaw.title.start': 'Tu equipo de',
    'openclaw.title.highlight': 'empleados virtuales',
    'openclaw.subtitle': 'Despliega agentes de IA especializados para manejar tareas complejas en estrategia, campañas, SEO y operaciones. Como tener todo un departamento trabajando 24/7.',
    'openclaw.agent.strategy.name': 'Agente de Estrategia',
    'openclaw.agent.strategy.status': 'Analizando market fit',
    'openclaw.agent.strategy.prompt': 'Analiza nuestro encaje producto-mercado actual e identifica las mayores brechas que debemos abordar.',
    'openclaw.agent.growth.name': 'Agente de Crecimiento',
    'openclaw.agent.growth.status': 'Generando Documento...',
    'openclaw.agent.growth.task': 'Estrategia Go-to-market',
    'openclaw.agent.data.name': 'Agente de Datos',
    'openclaw.agent.data.task': 'Definir PCI y Enriquecer Leads',
    'openclaw.agent.data.status': 'Procesando',
    'openclaw.agent.scraping.name': 'Agente Scraper',
    'openclaw.agent.scraping.status': 'Recopilando Inteligencia...',
    'openclaw.agent.scraping.task': 'Estrategia SEO y Competidores',
    'openclaw.agent.scraping.badge': 'Extraído',
    'openclaw.agent.marketing.name': 'Agente de Marketing',
    'openclaw.agent.marketing.task': 'Variantes de copy para anuncios',
    'openclaw.agent.marketing.prompt': 'Escribe 5 variantes de copy para un anuncio en Facebook...',
    
    'support.title': 'Con el respaldo de',
    
    'mockupslider.tab.crm': 'CRM',
    'mockupslider.tab.control': 'Centro de Control',
    'mockupslider.tab.reports': 'Reportes',
    'mockupslider.tab.inbox': 'Bandeja Omni',
    'mockupslider.tab.agents': 'Agentes IA',
    'mockupslider.tab.goals': 'Objetivos IA',
    
    'mockupslider.crm.newLeads': 'Nuevos Leads',
    'mockupslider.crm.engaged': 'Contactados por IA',
    'mockupslider.crm.meeting': 'Reunión Agendada',
    'mockupslider.crm.active': 'Activo',
    'mockupslider.crm.pending': 'Pendiente',
    'mockupslider.crm.meetingBooked': 'Reunión Agendada',
    'mockupslider.crm.agentClosed': 'El Agente IA cerró el trato automáticamente',
    'mockupslider.crm.agentTyping': 'Agente escribiendo...',
    
    'mockupslider.control.inProgress': 'En Progreso',
    'mockupslider.control.timeline': 'Línea de tiempo',
    'mockupslider.control.details': 'Detalles',
    'mockupslider.control.writeUpdate': 'Escribe una actualización o comentario...',
    'mockupslider.control.postUpdate': 'Publicar Actualización',
    'mockupslider.control.time1': 'Justo ahora',
    'mockupslider.control.msg1': 'He analizado con éxito el fragmento de datos y actualizado las tablas relevantes de la base de datos. La sincronización está ahora al 65%.',
    'mockupslider.control.time2': 'Hace 2 horas',
    'mockupslider.control.msg2': '¿Puedes proporcionar un resumen de las anomalías encontradas hasta ahora?',
    'mockupslider.control.time3': 'Hace 3 horas',
    'mockupslider.control.msg3': 'Extracción de datos inicial completada. Se encontraron 124 registros con identificadores faltantes.',
    'mockupslider.control.taskTitle': 'Sincronización y Análisis de Datos',
    'mockupslider.control.assignedTo': 'Tarea asignada al Agente IA',
    'mockupslider.control.taskDesc': 'Sincronizar 50k registros de la base de datos heredada y realizar detección de anomalías. Crear un informe detallado de cualquier identificador faltante o problemas de formato.',
    'mockupslider.control.badgeUpdate': 'Actualización de Tarea',
    'mockupslider.control.badgeUpdateDesc': 'Agente IA analizó 50k registros',
    'mockupslider.control.badgeAnomaly': 'Anomalía Detectada',
    
    'mockupslider.dashboard.title': 'Reportes Analíticos',
    'mockupslider.dashboard.period': 'Últimos 30 Días',
    'mockupslider.dashboard.stat1': 'Ingresos Totales',
    'mockupslider.dashboard.stat2': 'Usuarios Activos',
    'mockupslider.dashboard.stat3': 'Tasa de Conversión',
    'mockupslider.dashboard.stat4': 'Sesión Promedio',
    'mockupslider.dashboard.chartTitle': 'Resumen de Ingresos',
    
    'mockupslider.chat.search': 'Buscar mensajes...',
    'mockupslider.chat.team': 'Equipo de Ventas',
    'mockupslider.chat.msg1': '¡Gran trabajo en la nueva campaña!',
    'mockupslider.chat.msg2': 'He redactado 5 correos nuevos.',
    'mockupslider.chat.support': 'Soporte',
    'mockupslider.chat.msg3': 'Ticket #1042 resuelto.',
    'mockupslider.chat.yesterday': 'Ayer',
    'mockupslider.chat.marketing': 'Marketing',
    'mockupslider.chat.msg4': 'Los recursos están listos para revisión.',
    'mockupslider.chat.online': '4 miembros en línea',
    'mockupslider.chat.today': 'Hoy',
    'mockupslider.chat.bubble1': 'Hola equipo, ¿cómo va la nueva campaña de difusión?',
    'mockupslider.chat.bubble2': 'He analizado los datos iniciales. Las tasas de apertura han subido un 24% en comparación con la semana pasada. También he hecho seguimiento automático a 45 leads interesados.',
    'mockupslider.chat.bubble3': '¡Eso es increíble! ¿Puedes generar un informe para la reunión semanal?',
    'mockupslider.chat.bubble4': 'Absolutamente. Estoy compilando las métricas ahora.',
    'mockupslider.chat.reportName': 'informe_campaña_v1.pdf',
    'mockupslider.chat.reportSize': '1.2 MB • Listo',
    'mockupslider.chat.placeholder': 'Escribe un mensaje o pregunta a la IA...',
    'mockupslider.chat.autoReply': 'Respuesta Automática Enviada',
    'mockupslider.chat.autoReplyDesc': 'La IA manejó 45 consultas',
    'mockupslider.chat.leadQualified': 'Lead Calificado',
    'mockupslider.chat.leadQualifiedDesc': 'Transferido a Ventas',
    
    'mockupslider.agents.new': 'Nueva Makina',
    'mockupslider.agents.instance1': 'Instancia 1',
    'mockupslider.agents.instance2': 'Instancia 2',
    'mockupslider.agents.running': 'Ejecutando Tarea...',
    'mockupslider.agents.agentLog': 'Registro del Agente',
    'mockupslider.agents.log1': '[10:42:01] Navegando a la URL objetivo...',
    'mockupslider.agents.log2': '[10:42:03] Página cargada con éxito',
    'mockupslider.agents.log3': '[10:42:05] Escaneando elementos del DOM...',
    'mockupslider.agents.log4': '[10:42:06] Formulario objetivo encontrado, analizando campos',
    'mockupslider.agents.log5a': 'Ejecutando acción: LLENAR_FORMULARIO',
    'mockupslider.agents.log5b': '5 campos extraídos',
    'mockupslider.agents.log5c': 'Inyectando datos...',
    'mockupslider.agents.log6': '[10:42:08] Formulario lleno, esperando confirmación',
    'mockupslider.agents.instruction': 'Enviar instrucción...',
    'mockupslider.agents.deployed': 'Instancia Desplegada',
    'mockupslider.agents.deployedDesc': 'Ejecutando automatización de formulario',
    'mockupslider.agents.completed': 'Acción Completada',
    'mockupslider.agents.completedDesc': '5 campos extraídos e inyectados',
    
    'mockupslider.goals.tab1': 'Todos los Requisitos',
    'mockupslider.goals.tab2': 'Pendiente',
    'mockupslider.goals.tab3': 'Completado',
    'mockupslider.goals.newGoal': 'Nuevo Objetivo',
    'mockupslider.goals.type.feature': 'Característica',
    'mockupslider.goals.type.optimization': 'Optimización',
    'mockupslider.goals.type.bug': 'Error',
    'mockupslider.goals.status.inProgress': 'En Progreso',
    'mockupslider.goals.status.pending': 'Pendiente',
    'mockupslider.goals.status.completed': 'Completado',
    'mockupslider.goals.priority.critical': 'Crítico',
    'mockupslider.goals.priority.high': 'Alto',
    'mockupslider.goals.priority.medium': 'Medio',
    'mockupslider.goals.g1.title': 'Automatizar Configuración de Difusión',
    'mockupslider.goals.g2.title': 'Optimizar Velocidad de Landing Page',
    'mockupslider.goals.g3.title': 'Arreglar Límite de Tasa API',
    'mockupslider.goals.g4.title': 'Implementar Facturación Stripe',
    'mockupslider.goals.progress': 'Progreso',
    'mockupslider.goals.goalAchieved': 'Objetivo Logrado',
    'mockupslider.goals.goalAchievedDesc': 'Límite de Tasa API arreglado',
    'mockupslider.goals.autoPrioritization': 'Auto-priorización',
    'mockupslider.goals.autoPrioritizationDesc': 'Facturación Stripe movida a Alto',
    
    'auth.welcomeBack': 'Makinari es la Plataforma de Operaciones de Ingresos con Agentes que realmente realizan tareas por ti',
    'auth.welcomeAboard': 'Bienvenido a bordo',
    'auth.signInDesc': 'Inicia sesión para gestionar tus agentes de IA',
    'auth.signUpDesc': 'Comienza con la automatización de ventas',
    'auth.backedBy': 'Respaldado por',
    'auth.chip.gtm': 'GTM',
    'auth.chip.crm': 'CRM',
    'auth.chip.employees': 'Empleados',
    'auth.chip.openSource': 'Código Abierto',
    'auth.email': 'Correo electrónico',
    'auth.emailPlaceholder': 'nombre@ejemplo.com',
    'auth.password': 'Contraseña',
    'auth.passwordPlaceholder': 'Ingresa tu contraseña',
    'auth.forgotPassword': '¿Olvidaste tu contraseña?',
    'auth.signInBtn': 'Iniciar sesión',
    'auth.signUpBtn': 'Crear cuenta',
    'auth.orContinue': 'O CONTINÚA CON',
    'auth.whatsappBtn': 'Usa Makinari en WhatsApp',
    'auth.noAccount': '¿No tienes una cuenta?',
    'auth.signUpLink': 'Regístrate',
    'auth.hasAccount': '¿Ya tienes una cuenta?',
    'auth.signInLink': 'Inicia sesión',
    'auth.firstName': 'Nombre',
    'auth.lastName': 'Apellido',
    'auth.company': 'Empresa',
    'auth.companyOptional': 'Empresa (opcional)',
    'auth.creating': 'Creando cuenta...',
    'auth.sendReset': 'Enviar instrucciones',
    'auth.backToSignIn': 'Volver a iniciar sesión',

    'landing.scale.title.start': 'Todo lo que necesitas para',
    'landing.scale.title.highlight': 'escalar',
    'landing.scale.subtitle': 'Un conjunto completo de herramientas integradas en una plataforma perfecta. No más software desconectado.',
    'landing.outbound.badge': 'Escala Masiva',
    'landing.outbound.title': 'Sistema listo para Outbound',
    'landing.outbound.subtitle': 'Lanza campañas en minutos. Llega a miles de prospectos en múltiples canales con mensajes personalizados a escala, sin alcanzar los límites de spam.',
    'landing.outbound.deliveryRate': 'Tasa de Entrega',
    'landing.omnichannel.badge': 'Omnicanal',
    'landing.omnichannel.title': 'Automatización de canales',
    'landing.omnichannel.subtitle': 'Conecta Correo, WhatsApp, LinkedIn y más. Orquesta todas las comunicaciones en un solo lugar.',
    'landing.developer.title': 'MCP de código abierto',
    'landing.developer.subtitle': 'Construido para constructores. Alójalo en tu propia infraestructura con capacidades de código abierto.',
    'landing.seo.badge': 'Motor de Crecimiento',
    'landing.seo.title': 'Especialista en SEO y sitios',
    'landing.seo.subtitle': 'Optimiza tu presencia web automáticamente. Genera contenido perfeccionado para SEO, realiza un seguimiento de las clasificaciones en tiempo real y mejora el rendimiento del sitio continuamente.',
    'landing.content.title.start': 'Generación automática de',
    'landing.content.title.highlight': 'contenido',
    'landing.content.subtitle': 'Crea videos, publicaciones en redes sociales y correos electrónicos personalizados de alto impacto en piloto automático. Contenido coherente y acorde a la marca para cada canal.',

    'footer.product': 'Producto',
    'footer.product.features': 'Características',
    'footer.product.agents': 'Agentes IA',
    'footer.product.integrations': 'Integraciones',
    'footer.product.pricing': 'Precios',
    'footer.product.changelog': 'Registro de cambios',
    'footer.resources': 'Recursos',
    'footer.resources.docs': 'Documentación',
    'footer.resources.api': 'Referencia API',
    'footer.resources.community': 'Comunidad',
    'footer.resources.blog': 'Blog',
    'footer.resources.guides': 'Guías',
    'footer.company': 'Compañía',
    'footer.company.about': 'Sobre nosotros',
    'footer.company.careers': 'Empleo',
    'footer.company.contact': 'Contacto',
    'footer.company.privacy': 'Política de Privacidad',
    'footer.company.terms': 'Términos de Servicio',
    'footer.allSystemsOperational': 'Todos los sistemas operativos',
    'footer.rightsReserved': 'Makinari Inc. Todos los derechos reservados.',
    'footer.tagline': 'La Plataforma de Operaciones de Ingresos con agentes IA que realmente realizan tareas por ti. Escala tu outbound, contenido y crecimiento automáticamente.',
    'language.en': 'Inglés',
    'language.es': 'Español',
    'language.fr': 'Francés',
    'language.de': 'Alemán',
    'language.ja': 'Japonés',
    'virtual.badge': 'Operaciones',
    'virtual.title': 'Plataforma de Operaciones de Ingresos',
    'virtual.title.start': 'Plataforma de ',
    'virtual.title.highlight': 'Operaciones de Ingresos',
    'virtual.subtitle': 'Automatiza todo tu proceso de ventas con agentes de IA que trabajan 24/7. Desde la generación de leads hasta el cierre de acuerdos, nuestros empleados virtuales lo manejan todo.',
    'virtual.kanban.newLeads': 'Nuevos Leads',
    'virtual.kanban.engaged': 'Atendidos por IA',
    'virtual.kanban.meeting': 'Reunión Agendada',
    'virtual.kanban.active': 'Activo',
    'virtual.kanban.pending': 'Pendiente',
    'virtual.badge.title': 'Reunión Agendada',
    'virtual.badge.subtitle': 'Agente IA cerró el trato',
    'virtual.badge.typing': 'Agente escribiendo...',
  },
  fr: {
    'footer.product': 'Produit',
    'footer.resources': 'Ressources',
    'footer.company': 'Entreprise',
    'footer.allSystemsOperational': 'Tous les systèmes sont opérationnels',
    'footer.rightsReserved': 'Makinari Inc. Tous droits réservés.',
    'language.en': 'Anglais',
    'language.es': 'Espagnol',
    'language.fr': 'Français',
    'language.de': 'Allemand',
    'language.ja': 'Japonais',
    'virtual.badge': 'Opérations',
    'virtual.title': 'Plateforme d\'Opérations de Revenus',
    'virtual.title.start': 'Plateforme d\'',
    'virtual.title.highlight': 'Opérations de Revenus',
    'virtual.subtitle': 'Automatisez l\'ensemble de votre processus de vente avec des agents IA qui travaillent 24/7. De la génération de leads à la conclusion de contrats, nos employés virtuels gèrent tout.',
    'virtual.kanban.newLeads': 'Nouveaux Leads',
    'virtual.kanban.engaged': 'Engagés par IA',
    'virtual.kanban.meeting': 'Réunion Planifiée',
    'virtual.kanban.active': 'Actif',
    'virtual.kanban.pending': 'En attente',
    'virtual.badge.title': 'Réunion Planifiée',
    'virtual.badge.subtitle': 'L\'agent IA a conclu l\'accord',
    'virtual.badge.typing': 'Agent en train d\'écrire...',
  },
  de: {
    'footer.product': 'Produkt',
    'footer.resources': 'Ressourcen',
    'footer.company': 'Unternehmen',
    'footer.allSystemsOperational': 'Alle Systeme betriebsbereit',
    'footer.rightsReserved': 'Makinari Inc. Alle Rechte vorbehalten.',
    'language.en': 'Englisch',
    'language.es': 'Spanisch',
    'language.fr': 'Französisch',
    'language.de': 'Deutsch',
    'language.ja': 'Japanisch',
    'virtual.badge': 'Umsatzbetrieb',
    'virtual.title': 'Revenue Operations Plattform',
    'virtual.title.start': 'Revenue ',
    'virtual.title.highlight': 'Operations Plattform',
    'virtual.subtitle': 'Automatisieren Sie Ihren gesamten Verkaufsprozess mit KI-Agenten, die 24/7 arbeiten. Von der Lead-Generierung bis zum Abschluss von Geschäften übernehmen unsere virtuellen Mitarbeiter alles.',
    'virtual.kanban.newLeads': 'Neue Leads',
    'virtual.kanban.engaged': 'Von KI angesprochen',
    'virtual.kanban.meeting': 'Termin gebucht',
    'virtual.kanban.active': 'Aktiv',
    'virtual.kanban.pending': 'Ausstehend',
    'virtual.badge.title': 'Termin gebucht',
    'virtual.badge.subtitle': 'KI-Agent hat den Deal abgeschlossen',
    'virtual.badge.typing': 'Agent tippt...',
  },
  ja: {
    'footer.product': '製品',
    'footer.resources': 'リソース',
    'footer.company': '会社',
    'footer.allSystemsOperational': 'すべてのシステムが正常に稼働中',
    'footer.rightsReserved': 'Makinari Inc. 無断転載を禁じます。',
    'language.en': '英語',
    'language.es': 'スペイン語',
    'language.fr': 'フランス語',
    'language.de': 'ドイツ語',
    'language.ja': '日本語',
    'virtual.badge': 'レベニューオペレーション',
    'virtual.title': 'レベニューオペレーションプラットフォーム',
    'virtual.title.start': 'レベニュー',
    'virtual.title.highlight': 'オペレーションプラットフォーム',
    'virtual.subtitle': '24時間365日稼働するAIエージェントで営業プロセス全体を自動化。リードジェネレーションから成約まで、仮想従業員がすべてを処理します。',
    'virtual.kanban.newLeads': '新規リード',
    'virtual.kanban.engaged': 'AIが対応中',
    'virtual.kanban.meeting': 'ミーティング予約済み',
    'virtual.kanban.active': 'アクティブ',
    'virtual.kanban.pending': '保留中',
    'virtual.badge.title': 'ミーティング予約済み',
    'virtual.badge.subtitle': 'AIエージェントが成約しました',
    'virtual.badge.typing': 'エージェントが入力中...',
  },
};

// Map for localized assets like images
const localizedAssets: Record<SupportedLocale, Record<string, string>> = {
  en: {
    'logo.main': '/images/logo.png',
    'hero.image': '/images/hero-en.png',
  },
  es: {
    'logo.main': '/images/logo.png', // Fallback or localized
    'hero.image': '/images/hero-es.png',
  },
  fr: {
    'logo.main': '/images/logo.png',
    'hero.image': '/images/hero-fr.png',
  },
  de: {
    'logo.main': '/images/logo.png',
    'hero.image': '/images/hero-de.png',
  },
  ja: {
    'logo.main': '/images/logo.png',
    'hero.image': '/images/hero-ja.png',
  },
};

export const LocalizationProvider = ({ children }: { children: ReactNode }) => {
  const [locale, setLocaleState] = useState<SupportedLocale>(defaultLocale);
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    // Try to load from localStorage on mount
    const savedLocale = localStorage.getItem('makinari-locale') as SupportedLocale;
    if (savedLocale && Object.keys(translations).includes(savedLocale)) {
      setLocaleState(savedLocale);
    } else {
      // Try to guess from browser
      const browserLang = navigator.language.split('-')[0] as SupportedLocale;
      if (Object.keys(translations).includes(browserLang)) {
        setLocaleState(browserLang);
      }
    }
    setMounted(true);
  }, []);

  const setLocale = (newLocale: SupportedLocale) => {
    setLocaleState(newLocale);
    localStorage.setItem('makinari-locale', newLocale);
    // Optionally update the lang attribute on html tag
    document.documentElement.lang = newLocale;
  };

  const t = (key: string): string => {
    if (!mounted) return translations[defaultLocale][key] || key;
    return translations[locale][key] || translations[defaultLocale][key] || key;
  };

  const getAsset = (key: string): string => {
    if (!mounted) return localizedAssets[defaultLocale][key] || key;
    return localizedAssets[locale][key] || localizedAssets[defaultLocale][key] || key;
  };

  return (
    <LocalizationContext.Provider value={{ locale, setLocale, t, getAsset }}>
      {children}
    </LocalizationContext.Provider>
  );
};

export const useLocalization = () => {
  const context = useContext(LocalizationContext);
  if (context === undefined) {
    throw new Error('useLocalization must be used within a LocalizationProvider');
  }
  return context;
};
