import { buildBookingEmailHtml, sendBookingConfirmationEmail } from "@/app/book/send-booking-email";

jest.mock("@/app/documents/send-document-email", () => ({
  getSendGridConfig: jest.fn().mockReturnValue({
    apiKey: "SG.dummy",
    fromEmail: "no-reply@uncodie.com",
  }),
}));

describe("send-booking-email", () => {
  const dummyEvent = {
    title: "Intro Call",
    description: "Discussing stuff",
    location: "Google Meet",
    start: new Date("2026-09-02T22:00:00.000Z"),
    end: new Date("2026-09-02T22:30:00.000Z"),
    uid: "test@uncodie.com",
  };

  const dummyParams = {
    toEmail: "booker@example.com",
    toName: "Booker",
    ccEmails: ["guest@example.com"],
    bccEmail: "host@example.com",
    hostName: "Host User",
    siteName: "Test Site",
    eventName: "Intro Call",
    dateStr: "Sep 2, 2026",
    timeStr: "4:00 PM",
    timezone: "America/Mexico_City",
    location: "Google Meet",
    calendarEvent: dummyEvent,
    locale: "en",
  };

  describe("buildBookingEmailHtml", () => {
    it("builds the email HTML with correct styles and data", () => {
      const html = buildBookingEmailHtml(dummyParams);

      // Styles and Layout
      expect(html).toContain("1e1e2d"); // header bg
      expect(html).toContain("email-cta");
      expect(html).toContain("Notification automatically generated by");

      // Content
      expect(html).toContain("Hi Booker,");
      expect(html).toContain("Intro Call");
      expect(html).toContain("Host User");
      expect(html).toContain("Sep 2, 2026");
      expect(html).toContain("4:00 PM");
      expect(html).toContain("America/Mexico_City");
      expect(html).toContain("Google Meet");

      // Google Link
      expect(html).toContain("https://calendar.google.com/calendar/render");
    });
  });

  describe("sendBookingConfirmationEmail", () => {
    let fetchSpy: jest.SpyInstance;

    beforeEach(() => {
      fetchSpy = jest.spyOn(global, "fetch").mockResolvedValue({
        ok: true,
        json: async () => ({}),
      } as any);
    });

    afterEach(() => {
      jest.restoreAllMocks();
    });

    it("sends via SendGrid with proper payload", async () => {
      const result = await sendBookingConfirmationEmail(dummyParams);
      expect(result).toBe(true);

      expect(fetchSpy).toHaveBeenCalledTimes(1);
      const reqInit = fetchSpy.mock.calls[0][1];
      const payload = JSON.parse(reqInit.body);

      // Check structure
      expect(payload.from.email).toBe("no-reply@uncodie.com");
      expect(payload.from.name).toBe("Test Site");
      expect(payload.subject).toContain("Meeting confirmed");

      const personalizations = payload.personalizations[0];
      expect(personalizations.to).toEqual([{ email: "booker@example.com", name: "Booker" }]);
      expect(personalizations.cc).toEqual([{ email: "guest@example.com" }]);
      expect(personalizations.bcc).toEqual([{ email: "host@example.com" }]);

      // Check attachment
      expect(payload.attachments).toHaveLength(1);
      expect(payload.attachments[0].type).toBe("text/calendar");
      expect(payload.attachments[0].filename).toBe("invite.ics");
    });
  });
});
