import { journeyStage, makeBusinessHours, makeCopywriting, weekdaySchedule } from "../factories"

const SITE = "demo-ecom-es-456"
const USER = "demo-user-456"
const weekdays = ["monday", "tuesday", "wednesday", "thursday", "friday"] as string[]

export const ecomContext = {
  sitesPatch: {
    description: "Fast-fashion storefront for women, men, and accessories across Mexico City.",
    logo_url: "https://picsum.photos/seed/moda-rapida-logo/200/200",
  },
  settingsPatch: {
    about: "Moda Rápida designs and ships seasonal apparel for everyday wear, with same-week drops and in-store pickup in Polanco.",
    company_size: "11-50",
    industry: "Fashion retail",
    currency: "EUR",
    default_locale: "es",
    products: [
      { name: "Seasonal apparel", description: "Dresses, chinos, and knitwear.", cost: 18, lowest_sale_price: 39, target_sale_price: 59 },
      { name: "Accessories", description: "Belts and small leather goods.", cost: 12, lowest_sale_price: 25, target_sale_price: 35 },
    ],
    services: [
      { name: "Store pickup", description: "Same-day pickup at Polanco.", cost: 0, lowest_sale_price: 0, target_sale_price: 0 },
      { name: "Home delivery", description: "2-4 day shipping in CDMX.", cost: 4, lowest_sale_price: 6, target_sale_price: 8 },
    ],
    swot: {
      strengths: "Fast drops, strong Instagram reach, pickup in Polanco.",
      weaknesses: "Thin wholesale margins and limited size runs.",
      opportunities: "B2B boutiques and WhatsApp recovery flows.",
      threats: "Returns on trend pieces and paid-ad fatigue.",
    },
    locations: [
      {
        name: "Polanco store",
        address: "Av. Presidente Masaryk 111",
        city: "Mexico City",
        state: "CDMX",
        zip: "11560",
        country: "MX",
        restrictions: { enabled: false, included_addresses: [], excluded_addresses: [] },
      },
      {
        name: "CDMX warehouse",
        address: "Calle 8 240, Granjas San Antonio",
        city: "Mexico City",
        state: "CDMX",
        zip: "09070",
        country: "MX",
        restrictions: { enabled: false, included_addresses: [], excluded_addresses: [] },
      },
    ],
    business_hours: [
      makeBusinessHours("Storefront", "America/Mexico_City", weekdaySchedule([...weekdays, "saturday"], "11:00", "20:00")),
      makeBusinessHours("Warehouse", "America/Mexico_City", weekdaySchedule(weekdays, "08:00", "18:00")),
    ],
    marketing_budget: { total: 18000, available: 6400 },
    marketing_channels: [
      { name: "Instagram", type: "social" },
      { name: "Google Shopping", type: "paid" },
      { name: "Email", type: "owned" },
    ],
    social_media: [
      { platform: "instagram", url: "https://instagram.com/modarapida", handle: "modarapida", isActive: true },
      { platform: "facebook", url: "https://facebook.com/modarapida", handle: "modarapida", isActive: true },
      { platform: "tiktok", url: "https://tiktok.com/@modarapida", handle: "modarapida", isActive: false },
    ],
    team_members: [
      { email: "admin@moda-rapida.demo", role: "admin", name: "Demo Admin", position: "Owner" },
      { email: "sofia@moda-rapida.demo", role: "create", name: "Sofia Ruiz", position: "Store lead" },
    ],
    calendars: [
      {
        id: "cal-ecom-styling",
        name: "Personal styling",
        slug: "styling",
        member_ids: [USER],
        description: "In-store styling slots",
        location: "Polanco store",
        duration: 30,
        buffer: 10,
        created_at: new Date().toISOString(),
      },
    ],
    competitors: [
      { url: "https://zara.com", name: "Zara" },
      { url: "https://shein.com", name: "SHEIN" },
    ],
    focus_mode: 70,
    business_model: { b2b: true, b2c: true, b2b2c: false },
    goals: {
      quarterly: "Grow repeat buyers to 35% of orders.",
      yearly: "Open a second pickup point and hit 12k monthly orders.",
      fiveYear: "Become the default mid-price streetwear brand in LATAM.",
      tenYear: "Own the full design-to-door cycle across three countries.",
    },
    branding: {
      brand_essence: "Everyday pieces that feel current without the wait.",
      brand_personality: "Bold, urban, and approachable.",
      brand_benefits: "Trend-right fits that ship this week.",
      brand_attributes: "Color-forward, size-inclusive, city-ready.",
      brand_values: "Speed, honesty on stock, and easy returns.",
      brand_promise: "Look current this weekend, not next season.",
      brand_archetype: "explorer",
      primary_color: "#111111",
      secondary_color: "#F4EDE4",
      accent_color: "#E11D48",
      success_color: "#16A34A",
      warning_color: "#F59E0B",
      error_color: "#DC2626",
      background_color: "#FFFFFF",
      surface_color: "#FAFAF9",
      primary_font: "Inter",
      secondary_font: "Playfair Display",
      font_size_scale: "medium",
      communication_style: "casual",
      personality_traits: ["confident", "playful", "direct"],
      emotions_to_evoke: ["excitement", "ease"],
      preferred_phrases: ["Drop of the week", "Ready for pickup"],
      forbidden_words: ["cheap", "fast fashion waste"],
      do_list: ["Show real stock photos", "Lead with fit and fabric"],
      dont_list: ["Overpromise restocks", "Use stock-model-only lookbooks"],
    },
    customer_journey: {
      awareness: journeyStage(["Instagram reels", "Google Shopping"], ["Reach", "New sessions"], ["Publish drop teasers"]),
      consideration: journeyStage(["Lookbooks", "Size guides"], ["PDP views"], ["Retarget cart viewers"]),
      decision: journeyStage(["VERANO20", "Free pickup"], ["Add to cart"], ["Recover unpaid carts"]),
      purchase: journeyStage(["Checkout", "Pickup slot"], ["Orders", "AOV"], ["Confirm payment"]),
      retention: journeyStage(["Reorder email", "Loyalty"], ["Repeat rate"], ["Invite to next drop"]),
      referral: journeyStage(["Share-the-look"], ["Referral codes"], ["Reward boutiques"]),
    },
    channels: {
      website: {
        enabled: true,
        track_visitors: true,
        track_actions: true,
        record_screen: false,
        enable_chat: true,
        chat_accent_color: "#E11D48",
        allow_anonymous_messages: true,
        chat_position: "bottom-right",
        welcome_message: "Need a size or pickup slot? We can help.",
        chat_title: "Moda Rápida",
      },
    },
    shop: {
      hero_title: "New drop, ready this week",
      hero_subtitle: "Dresses, chinos, and accessories shipping from CDMX.",
      hero_cta_label: "Shop the drop",
      hero_cta_destination_type: "scroll",
      hero_cta_destination_value: "",
      hero_order_bar: true,
      hero_image_url: "https://picsum.photos/seed/moda-rapida-hero/1200/600",
      free_shipping_threshold: 80,
      delivery_time_min: 2,
      delivery_time_max: 4,
      return_policy_summary: "14-day returns on unused items",
      trust_badges: [
        { title: "Pickup today", subtitle: "Polanco store", icon: "store" },
        { title: "Easy returns", subtitle: "14 days", icon: "refresh" },
      ],
      payment_methods: ["card", "cash_on_pickup", "bank_transfer"],
      default_delivery_options: ["pickup", "ship"],
    },
    printers: {
      devices: [
        {
          id: "printer-ecom-pos",
          name: "Polanco receipt printer",
          transport: "usb",
          paperWidthMm: 80,
          copies: 1,
          enabled: true,
          modules: { pos: true, orders: true, inventory: false },
          autoPrint: { posReceipt: true, kitchenTicket: false, orderDelta: false, inventoryLabel: false },
        },
      ],
    },
    activities: {
      daily_resume_and_stand_up: { status: "default" },
      local_lead_generation: { status: "inactive" },
      icp_lead_generation: { status: "inactive" },
      leads_initial_cold_outreach: { status: "inactive" },
      leads_follow_up: { status: "default" },
      email_sync: { status: "default" },
      assign_leads_to_team: { status: "inactive" },
      notify_team_on_inbound_conversations: { status: "default" },
      supervise_conversations: { status: "inactive" },
    },
  },
  copywriting: [
    makeCopywriting({
      id: "copy-ecom-1",
      siteId: SITE,
      userId: USER,
      title: "Summer drop subject",
      content: "VERANO20 is live — new dresses and chinos ready for Polanco pickup.",
      copy_type: "email_subject",
      target_audience: "Repeat buyers",
      use_case: "Drop announcement",
      tags: ["email", "drop"],
    }),
    makeCopywriting({
      id: "copy-ecom-2",
      siteId: SITE,
      userId: USER,
      title: "Cart recovery",
      content: "Your bag is waiting. Use VERANO20 before the weekend drop sells out.",
      copy_type: "follow_up_email",
      target_audience: "Abandoned carts",
      use_case: "Cart recovery",
      tags: ["email", "recovery"],
    }),
  ],
}
