import { getSendGridConfig } from "@/app/documents/send-document-email";
import { documentT, resolveDocumentLocale } from "@/app/lib/i18n/document-t";
import { emailBadge, emailBrandHeadTags, emailCtaButton, escapeHtml } from "@/lib/emails/brand";
import { buildGoogleCalendarUrl, buildIcs, CalendarEvent } from "@/lib/calendar/invite";

export interface SendBookingEmailParams {
  toEmail: string;
  toName: string;
  ccEmails?: string[];
  bccEmail?: string;
  
  hostName: string;
  siteName: string;
  siteLogoUrl?: string | null;
  
  eventName: string;
  dateStr: string; // localized string for display
  timeStr: string; // localized string for display
  timezone: string;
  location?: string;
  
  calendarEvent: CalendarEvent;
  locale?: string;
}

export function buildBookingEmailHtml(params: SendBookingEmailParams): string {
  const locale = resolveDocumentLocale(params.locale);
  const greeting = documentT(locale, "booking.email.greetingNamed", {
    name: escapeHtml(params.toName),
  });
  const googleLink = buildGoogleCalendarUrl(params.calendarEvent);

  const titleSafe = escapeHtml(params.eventName);
  const hostSafe = escapeHtml(params.hostName);
  const locationSafe = escapeHtml(params.location || "");
  const ctaLabel = documentT(locale, "booking.email.addToGoogle");
  const confirmedLabel = documentT(locale, "booking.email.confirmed");

  return `
    <!DOCTYPE html>
    <html lang="${locale}">
    <head>
      ${emailBrandHeadTags()}
      <title>${escapeHtml(params.eventName)}</title>
    </head>
    <body style="margin: 0; padding: 0; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; background-color: #f8fafc; line-height: 1.6;">
      <div class="email-card" style="max-width: 600px; margin: 40px auto; background-color: #ffffff; border-radius: 12px; box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1); overflow: hidden;">
        
        <div class="email-header" style="background: #1e1e2d; padding: 32px 40px; text-align: center;">
          ${params.siteLogoUrl ? `
            <img src="${escapeHtml(params.siteLogoUrl)}" alt="${escapeHtml(params.siteName)} Logo" style="width: 64px; height: 64px; border-radius: 50%; object-fit: cover; display: block; margin: 0 auto;" />
          ` : ''}
          <h1 class="email-header-title" style="margin: 16px 0 0; color: #ffffff; font-size: 24px; font-weight: 600;">${documentT(locale, "booking.email.title")}</h1>
        </div>

        <div style="padding: 40px;">
          <div style="margin-bottom: 24px;">
            ${emailBadge(confirmedLabel)}
          </div>
          
          <p class="email-text" style="margin: 0 0 24px; font-size: 16px; color: #111111;">
            ${greeting}
          </p>
          
          <p class="email-text" style="margin: 0 0 24px; font-size: 16px; color: #111111;">
            ${documentT(locale, "booking.email.body")}
          </p>

          <div class="email-panel" style="background-color: #f0f0f5; padding: 24px; border-radius: 8px; border: 1px solid #e4e4e7; margin-bottom: 32px;">
            <ul style="list-style: none; padding: 0; margin: 0;">
              <li style="margin-bottom: 12px;"><strong style="color: #111111;">${documentT(locale, "booking.details.event")}:</strong> ${titleSafe}</li>
              <li style="margin-bottom: 12px;"><strong style="color: #111111;">${documentT(locale, "booking.details.date")}:</strong> ${escapeHtml(params.dateStr)}</li>
              <li style="margin-bottom: 12px;"><strong style="color: #111111;">${documentT(locale, "booking.details.time")}:</strong> ${escapeHtml(params.timeStr)} (${escapeHtml(params.timezone)})</li>
              <li style="margin-bottom: 12px;"><strong style="color: #111111;">${documentT(locale, "booking.details.with")}:</strong> ${hostSafe}</li>
              ${params.location ? `<li style="margin-bottom: 0;"><strong style="color: #111111;">Location:</strong> ${locationSafe}</li>` : ''}
            </ul>
          </div>

          ${emailCtaButton(googleLink, ctaLabel)}
          
          <p class="email-muted" style="margin: 24px 0 0; font-size: 14px; text-align: center;">
            ${documentT(locale, "booking.email.icsAttached")}
          </p>
        </div>

        <div style="background-color: #f8fafc; padding: 24px 40px; border-top: 1px solid #e2e8f0;">
          <p class="email-muted" style="margin: 0; color: #52525b; font-size: 14px; text-align: center; line-height: 1.5;">
            Notification automatically generated by ${process.env.UNCODIE_COMPANY_NAME || 'Makinari'}.<br>
          </p>
        </div>
      </div>
      
      <div style="text-align: center; margin: 24px 0;">
        <p class="email-muted" style="margin: 0; color: #71717a; font-size: 12px;">
          Powered by <strong style="color: #000000;">${process.env.UNCODIE_BRANDING_TEXT || 'Makinari, your AI Sales Team'}</strong>
        </p>
      </div>
    </body>
    </html>
  `;
}

export async function sendBookingConfirmationEmail(params: SendBookingEmailParams): Promise<boolean> {
  const mailConfig = getSendGridConfig();
  if (!mailConfig) {
    console.log("[BookingEmail] SendGrid not configured, skipping email.");
    return false;
  }

  const locale = resolveDocumentLocale(params.locale);
  const subject = documentT(locale, "booking.email.subject", { event: params.eventName, siteName: params.siteName });
  const html = buildBookingEmailHtml(params);
  
  const icsStr = buildIcs(params.calendarEvent);
  const icsBase64 = Buffer.from(icsStr).toString("base64");

  const toList = [{ email: params.toEmail, name: params.toName }];
  const ccList = (params.ccEmails || []).map(e => ({ email: e }));
  
  const personalizations: any = { to: toList };
  if (ccList.length > 0) personalizations.cc = ccList;
  if (params.bccEmail && params.bccEmail !== params.toEmail) {
    personalizations.bcc = [{ email: params.bccEmail }];
  }

  const payload = {
    personalizations: [personalizations],
    from: { email: mailConfig.fromEmail, name: params.siteName },
    subject,
    content: [
      { type: "text/html", value: html }
    ],
    attachments: [
      {
        content: icsBase64,
        filename: "invite.ics",
        type: "text/calendar",
        disposition: "attachment"
      }
    ]
  };

  try {
    const res = await fetch("https://api.sendgrid.com/v3/mail/send", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${mailConfig.apiKey}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify(payload),
    });

    if (!res.ok) {
      const detail = await res.text().catch(() => "");
      console.error(`[BookingEmail] SendGrid error (${res.status}):`, detail);
      return false;
    }
    return true;
  } catch (error) {
    console.error("[BookingEmail] Fetch error:", error);
    return false;
  }
}
