import { journeyStage, makeBusinessHours, makeCopywriting, weekdaySchedule } from "../factories"

const SITE = "demo-habituall"
const USER = "demo-user-123"
const studioDays = ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday"] as string[]

export const habituallContext = {
  sitesPatch: {
    name: "HabitUall Studio",
    description: "Coworking desks, class studios, and memberships for clubs in Mexico City.",
    logo_url: "https://picsum.photos/seed/habituall-logo/200/200",
  },
  settingsPatch: {
    about: "HabitUall runs studio classes, day passes, and coworking desks from Roma and Centro, with memberships that unlock both spaces.",
    company_size: "11-50",
    industry: "Fitness and coworking",
    currency: "MXN",
    default_locale: "es",
    products: [
      { name: "10-class pass", description: "Credits for any group class.", cost: 400, lowest_sale_price: 1800, target_sale_price: 1800 },
      { name: "Day pass", description: "One-day access to coworking and cafe.", cost: 80, lowest_sale_price: 250, target_sale_price: 250 },
    ],
    services: [
      { name: "Yoga 60m", description: "All-levels class in Studio Roma.", cost: 80, lowest_sale_price: 220, target_sale_price: 220 },
      { name: "Monthly membership", description: "Unlimited classes plus desk access.", cost: 600, lowest_sale_price: 1890, target_sale_price: 1890 },
    ],
    swot: {
      strengths: "Two locations and a sticky membership.",
      weaknesses: "Peak-hour class capacity is tight.",
      opportunities: "Corporate desk packs and weekend workshops.",
      threats: "No-shows and seasonal membership pauses.",
    },
    locations: [
      {
        name: "Studio Roma",
        address: "Calle Orizaba 87",
        city: "Mexico City",
        state: "CDMX",
        zip: "06700",
        country: "MX",
        restrictions: { enabled: false, included_addresses: [], excluded_addresses: [] },
      },
      {
        name: "Coworking Centro",
        address: "Av. Juárez 42",
        city: "Mexico City",
        state: "CDMX",
        zip: "06010",
        country: "MX",
        restrictions: { enabled: false, included_addresses: [], excluded_addresses: [] },
      },
    ],
    business_hours: [
      makeBusinessHours("Studio Roma", "America/Mexico_City", weekdaySchedule(studioDays, "07:00", "21:00")),
      makeBusinessHours("Coworking Centro", "America/Mexico_City", weekdaySchedule(studioDays, "08:00", "20:00")),
    ],
    marketing_budget: { total: 9000, available: 3100 },
    marketing_channels: [
      { name: "Instagram", type: "social" },
      { name: "WhatsApp", type: "owned" },
      { name: "Local partnerships", type: "offline" },
    ],
    social_media: [
      { platform: "instagram", url: "https://instagram.com/habituall", handle: "habituall", isActive: true },
      { platform: "whatsapp", url: "https://wa.me/525512345678", handle: "+52 55 1234 5678", isActive: true },
    ],
    team_members: [
      { email: "admin@acme-habituall.demo", role: "admin", name: "Demo Admin", position: "Studio owner" },
      { email: "front@habituall.demo", role: "create", name: "Lucia Vega", position: "Front desk" },
    ],
    calendars: [
      {
        id: "cal-hab-intro",
        name: "Intro class",
        slug: "intro-class",
        member_ids: [USER],
        description: "First-visit intro slots",
        location: "Studio Roma",
        duration: 60,
        buffer: 15,
        created_at: new Date().toISOString(),
      },
    ],
    competitors: [
      { url: "https://soul-cycle.com", name: "Boutique studios" },
      { url: "https://wework.com", name: "Coworking chains" },
    ],
    focus_mode: 65,
    business_model: { b2b: true, b2c: true, b2b2c: false },
    goals: {
      quarterly: "Fill 80% of weekday yoga spots.",
      yearly: "Reach 400 active members across both locations.",
      fiveYear: "Open a third neighborhood studio.",
      tenYear: "License the HabitUall ops playbook to other clubs.",
    },
    branding: {
      brand_essence: "A daily habit that feels like belonging.",
      brand_personality: "Warm, local, and disciplined.",
      brand_benefits: "Classes, desks, and cafe in one membership.",
      brand_attributes: "Neighborhood, consistent, welcoming.",
      brand_values: "Show up, share space, stay kind.",
      brand_promise: "There is a spot for you this week.",
      brand_archetype: "caregiver",
      primary_color: "#1F3A2E",
      secondary_color: "#F3EDE3",
      accent_color: "#C45C26",
      success_color: "#2F855A",
      warning_color: "#C05621",
      error_color: "#C53030",
      background_color: "#FFFbf5",
      surface_color: "#F7F1E8",
      primary_font: "Source Sans 3",
      secondary_font: "Fraunces",
      font_size_scale: "medium",
      communication_style: "friendly",
      personality_traits: ["welcoming", "steady", "local"],
      emotions_to_evoke: ["calm", "belonging"],
      preferred_phrases: ["See you on the mat", "Your desk is ready"],
      forbidden_words: ["grind", "hustle"],
      do_list: ["Name the studio", "Invite to a specific class"],
      dont_list: ["Sell unlimited hype", "Shame no-shows"],
    },
    customer_journey: {
      awareness: journeyStage(["Neighborhood flyers", "Instagram"], ["Walk-ins"], ["Invite first class"]),
      consideration: journeyStage(["Intro class", "Day pass"], ["Trial bookings"], ["Confirm spot"]),
      decision: journeyStage(["10-class pass", "Membership"], ["Conversions"], ["Offer front-desk help"]),
      purchase: journeyStage(["POS", "Online checkout"], ["New members"], ["Issue entitlement"]),
      retention: journeyStage(["Class reminder", "Check-in"], ["Visits / week"], ["Offer pause instead of cancel"]),
      referral: journeyStage(["Bring a friend"], ["Referral passes"], ["Thank members in-studio"]),
    },
    channels: {
      website: {
        enabled: true,
        track_visitors: true,
        track_actions: true,
        record_screen: false,
        enable_chat: true,
        chat_accent_color: "#C45C26",
        allow_anonymous_messages: true,
        chat_position: "bottom-right",
        welcome_message: "Looking for a class or a desk today? Tell us which location.",
        chat_title: "HabitUall desk",
      },
    },
    shop: {
      hero_title: "Classes and desks, one membership",
      hero_subtitle: "Book yoga in Roma or grab a day pass in Centro.",
      hero_cta_label: "See the schedule",
      hero_cta_destination_type: "scroll",
      hero_order_bar: false,
      payment_methods: ["card", "cash_on_pickup"],
      default_delivery_options: ["none"],
    },
    printers: { devices: [] },
    activities: {
      daily_resume_and_stand_up: { status: "default" },
      local_lead_generation: { status: "default" },
      icp_lead_generation: { status: "inactive" },
      leads_initial_cold_outreach: { status: "inactive" },
      leads_follow_up: { status: "default" },
      email_sync: { status: "default" },
      assign_leads_to_team: { status: "inactive" },
      notify_team_on_inbound_conversations: { status: "default" },
      supervise_conversations: { status: "inactive" },
    },
  },
  copywriting: [
    makeCopywriting({
      id: "copy-hab-1",
      siteId: SITE,
      userId: USER,
      title: "Class confirmation",
      content: "You are in for Yoga 60m at Studio Roma. Arrive 10 minutes early so we can hold your spot.",
      copy_type: "nurture_email",
      target_audience: "Class bookings",
      use_case: "Reservation confirmation",
      tags: ["classes"],
    }),
    makeCopywriting({
      id: "copy-hab-2",
      siteId: SITE,
      userId: USER,
      title: "Membership invite",
      content: "Loved your first week? The monthly membership unlocks classes and a Centro desk.",
      copy_type: "follow_up_email",
      target_audience: "Trial members",
      use_case: "Upgrade",
      tags: ["membership"],
    }),
  ],
}
