import { documentT, resolveDocumentLocale } from "@/app/lib/i18n/document-t"
import { emailBrandHeadTags, emailCtaButton, escapeHtml } from "@/lib/emails/brand"

export type DocumentEmailI18nPrefix = "quotations" | "sales" | "orders" | "bills"

export type SendDocumentEmailParams = {
  toEmail: string
  toName?: string | null
  fromEmail: string
  fromName: string
  subject: string
  siteName: string
  docRef: string
  totalLabel: string
  viewLink: string
  checkoutLink?: string | null
  pdfBase64: string
  pdfFilename: string
  apiKey: string
  locale?: string | null
  i18nPrefix: DocumentEmailI18nPrefix
}

export function getSendGridConfig(): {
  apiKey: string
  fromEmail: string
  fromName?: string
} | null {
  const apiKey = process.env.SENDGRID_API_KEY
  const fromEmail = process.env.SENDGRID_FROM_EMAIL
  if (!apiKey || !fromEmail) return null
  return {
    apiKey,
    fromEmail,
    fromName: process.env.SENDGRID_FROM_NAME || undefined,
  }
}

export function buildDocumentEmailHtml(params: {
  toName?: string | null
  siteName: string
  docRef: string
  totalLabel: string
  viewLink: string
  checkoutLink?: string | null
  locale?: string | null
  i18nPrefix: DocumentEmailI18nPrefix
}): string {
  const locale = resolveDocumentLocale(params.locale)
  const p = params.i18nPrefix
  const greeting = params.toName
    ? documentT(locale, `${p}.email.greetingNamed`, { name: params.toName })
    : documentT(locale, `${p}.email.greeting`)
  const body = documentT(locale, `${p}.email.body`, {
    siteName: params.siteName,
    docRef: params.docRef,
    quoteRef: params.docRef,
    totalLabel: params.totalLabel,
  })
  const pdfNote = documentT(locale, `${p}.email.pdfAttached`)
  const cta = documentT(locale, `${p}.email.viewCta`)
  const payCta = documentT(locale, `${p}.email.payCta`) || "Pay Now"
  const orOpen = params.checkoutLink 
    ? documentT(locale, `${p}.email.orOpen`, { link: params.checkoutLink }) 
    : documentT(locale, `${p}.email.orOpen`, { link: params.viewLink })
  const title = buildDocumentEmailSubject(params)

  return `
    <!DOCTYPE html>
    <html lang="${locale}">
    <head>
      ${emailBrandHeadTags()}
      <title>${escapeHtml(title)}</title>
    </head>
    <body style="margin: 0; padding: 0; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; background-color: #f8fafc; line-height: 1.6;">
      <div class="email-card" style="max-width: 600px; margin: 40px auto; background-color: #ffffff; border-radius: 12px; box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1); overflow: hidden;">
        
        <div class="email-header" style="background: #1e1e2d; padding: 32px 40px; text-align: center;">
          <h1 class="email-header-title" style="margin: 16px 0 0; color: #ffffff; font-size: 24px; font-weight: 600;">${escapeHtml(params.siteName)}</h1>
        </div>

        <div style="padding: 40px;">
          
          <p class="email-text" style="margin: 0 0 24px; font-size: 16px; color: #111111;">
            ${greeting}
          </p>
          
          <p class="email-text" style="margin: 0 0 24px; font-size: 16px; color: #111111;">
            ${body}
          </p>

          <p class="email-muted" style="margin: 0 0 24px; font-size: 14px; color: #52525b;">
            ${pdfNote}
          </p>

          ${params.checkoutLink ? emailCtaButton(params.checkoutLink, payCta) : ''}
          ${params.checkoutLink ? `
          <p class="email-muted" style="margin: 24px 0 0; font-size: 14px; text-align: center;">
            ${orOpen}
          </p>
          ` : `
          ${emailCtaButton(params.viewLink, cta)}
          <p class="email-muted" style="margin: 24px 0 0; font-size: 14px; text-align: center;">
            ${orOpen}
          </p>
          `}
        </div>

        <div style="background-color: #f8fafc; padding: 24px 40px; border-top: 1px solid #e2e8f0;">
          <p class="email-muted" style="margin: 0; color: #52525b; font-size: 14px; text-align: center; line-height: 1.5;">
            Notification automatically generated by ${process.env.UNCODIE_COMPANY_NAME || 'Makinari'}.<br>
          </p>
        </div>
      </div>
      
      <div style="text-align: center; margin: 24px 0;">
        <p class="email-muted" style="margin: 0; color: #71717a; font-size: 12px;">
          Powered by <strong style="color: #000000;">${process.env.UNCODIE_BRANDING_TEXT || 'Makinari, your AI Sales Team'}</strong>
        </p>
      </div>
    </body>
    </html>
  `;
}

export function buildDocumentEmailSubject(params: {
  siteName: string
  docRef: string
  locale?: string | null
  i18nPrefix: DocumentEmailI18nPrefix
}): string {
  return documentT(resolveDocumentLocale(params.locale), `${params.i18nPrefix}.email.subject`, {
    docRef: params.docRef,
    quoteRef: params.docRef,
    siteName: params.siteName,
  })
}

export function buildDocumentSendGridPayload(params: SendDocumentEmailParams) {
  const locale = resolveDocumentLocale(params.locale)
  const p = params.i18nPrefix
  const html = buildDocumentEmailHtml({
    toName: params.toName,
    siteName: params.siteName,
    docRef: params.docRef,
    totalLabel: params.totalLabel,
    viewLink: params.viewLink,
    checkoutLink: params.checkoutLink,
    locale,
    i18nPrefix: p,
  })
  const greeting = params.toName
    ? documentT(locale, `${p}.email.greetingNamed`, { name: params.toName })
    : documentT(locale, `${p}.email.greeting`)
  const text = [
    greeting,
    "",
    documentT(locale, `${p}.email.textBody`, {
      siteName: params.siteName,
      docRef: params.docRef,
      quoteRef: params.docRef,
      totalLabel: params.totalLabel,
    }),
    documentT(locale, `${p}.email.textPdfAttached`),
    params.checkoutLink ? documentT(locale, `${p}.email.textReview`, { link: params.checkoutLink }) : documentT(locale, `${p}.email.textReview`, { link: params.viewLink }),
  ].join("\n")

  return {
    personalizations: [
      {
        to: [{ email: params.toEmail, ...(params.toName ? { name: params.toName } : {}) }],
      },
    ],
    from: { email: params.fromEmail, name: params.fromName },
    subject: params.subject,
    content: [
      { type: "text/plain", value: text },
      { type: "text/html", value: html },
    ],
    attachments: [
      {
        content: params.pdfBase64,
        filename: params.pdfFilename,
        type: "application/pdf",
        disposition: "attachment",
      },
    ],
  }
}

export async function sendDocumentEmailViaSendGrid(
  params: SendDocumentEmailParams
): Promise<{ success: true } | { error: string }> {
  const payload = buildDocumentSendGridPayload(params)
  const res = await fetch("https://api.sendgrid.com/v3/mail/send", {
    method: "POST",
    headers: {
      Authorization: `Bearer ${params.apiKey}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify(payload),
  })

  if (!res.ok) {
    const detail = await res.text().catch(() => "")
    return {
      error: `Failed to send email (${res.status})${detail ? `: ${detail.slice(0, 200)}` : ""}`,
    }
  }

  return { success: true }
}
