import { z } from "zod"

// Definir el schema de respuesta
export const LeadSchema = z.object({
  leads: z.array(z.object({
    id: z.string(),
    buyer_user_id: z.string().nullable().optional(),
    name: z.string(),
    email: z.string(),
    personal_email: z.string().nullable(),
    phone: z.string().nullable(),
    company: z.object({
      name: z.string().optional(),
      website: z.string().optional(),
      industry: z.string().optional(),
      size: z.string().optional(),
      annual_revenue: z.string().optional(),
      founded: z.string().optional(),
      description: z.string().optional(),
      address: z.object({
        street: z.string().optional(),
        city: z.string().optional(),
        state: z.string().optional(),
        zipcode: z.string().optional(),
        country: z.string().optional(),
      }).optional(),
    }).nullable(),
    company_id: z.string().nullable(),
    position: z.string().nullable(),
    segment_id: z.string().nullable(),
    campaign_id: z.string().nullable(),
    status: z.enum(["new", "contacted", "qualified", "cold", "converted", "lost", "not_qualified"]),
    notes: z.string().nullable(),
    origin: z.string().nullable(),
    created_at: z.string(),
    updated_at: z.string(),
    last_contact: z.string().nullable(),
    site_id: z.string(),
    user_id: z.string(),
    birthday: z.string().nullable(),
    language: z.string().nullable(),
    social_networks: z.object({
      linkedin: z.string().optional().nullable(),
    twitter: z.string().optional().nullable(),
    facebook: z.string().optional().nullable(),
    instagram: z.string().optional().nullable(),
    tiktok: z.string().optional().nullable(),
    youtube: z.string().optional().nullable(),
    whatsapp: z.string().optional().nullable(),
    pinterest: z.string().optional().nullable(),
    threads: z.string().optional().nullable(),
  }).nullable(),
    address: z.object({
      street: z.string().optional(),
      city: z.string().optional(),
      state: z.string().optional(),
      zipcode: z.string().optional(),
      country: z.string().optional(),
    }).nullable(),
    attribution: z.object({
      user_id: z.string(),
      user_name: z.string(),
      date: z.string(),
      final_amount: z.number().optional(),
      is_market_fit_influenced: z.boolean(),
      notes: z.string().optional(),
    }).nullable().optional(),
    assignee_id: z.string().nullable().optional(),
  })).nullable(),
  error: z.string().optional()
})

export type LeadResponse = z.infer<typeof LeadSchema>
// Schema for single lead response
export const SingleLeadSchema = z.object({
  lead: z.object({
    id: z.string(),
    buyer_user_id: z.string().nullable().optional(),
    name: z.string(),
    email: z.string(),
    personal_email: z.string().nullable(),
    phone: z.string().nullable(),
    company: z.object({
      name: z.string().optional(),
      website: z.string().optional(),
      industry: z.string().optional(),
      size: z.string().optional(),
      annual_revenue: z.string().optional(),
      founded: z.string().optional(),
      description: z.string().optional(),
      address: z.object({
        street: z.string().optional(),
        city: z.string().optional(),
        state: z.string().optional(),
        zipcode: z.string().optional(),
        country: z.string().optional(),
      }).optional(),
    }).nullable(),
    company_id: z.string().nullable(),
    position: z.string().nullable(),
    segment_id: z.string().nullable(),
    campaign_id: z.string().nullable(),
    status: z.enum(["new", "contacted", "qualified", "cold", "converted", "lost", "not_qualified"]),
    notes: z.string().nullable(),
    origin: z.string().nullable(),
    created_at: z.string(),
    updated_at: z.string(),
    last_contact: z.string().nullable(),
    site_id: z.string(),
    user_id: z.string(),
    birthday: z.string().nullable(),
    language: z.string().nullable(),
    social_networks: z.object({
      linkedin: z.string().optional().nullable(),
    twitter: z.string().optional().nullable(),
    facebook: z.string().optional().nullable(),
    instagram: z.string().optional().nullable(),
    tiktok: z.string().optional().nullable(),
    youtube: z.string().optional().nullable(),
    whatsapp: z.string().optional().nullable(),
    pinterest: z.string().optional().nullable(),
    threads: z.string().optional().nullable(),
  }).nullable(),
    address: z.object({
      street: z.string().optional(),
      city: z.string().optional(),
      state: z.string().optional(),
      zipcode: z.string().optional(),
      country: z.string().optional(),
    }).nullable(),
    attribution: z.object({
      user_id: z.string(),
      user_name: z.string(),
      date: z.string(),
      final_amount: z.number().optional(),
      is_market_fit_influenced: z.boolean(),
      notes: z.string().optional(),
    }).nullable().optional(),
    assignee_id: z.string().nullable().optional(),
  }).nullable(),
  error: z.string().optional()
})

export type SingleLeadResponse = z.infer<typeof SingleLeadSchema>
// Schema para validar los datos de entrada al crear un lead
export const CreateLeadSchema = z.object({
  name: z.string().min(1, "Name is required").optional().or(z.literal("")),
  email: z.string().email("Invalid email address").optional().nullable().or(z.literal("")),
  personal_email: z.string().email("Invalid personal email address").optional().nullable().or(z.literal("")),
  phone: z.string().optional().nullable().or(z.literal("")),
  company: z.union([
    z.string(),
    z.object({
      name: z.string().optional(),
      website: z.string().optional(),
      industry: z.string().optional(),
      size: z.string().optional(),
      annual_revenue: z.string().optional(),
      founded: z.string().optional(),
      description: z.string().optional(),
      domain: z.string().optional(),
      location: z.any().optional(), // Allow any location structure
      external_organization_id: z.union([z.string(), z.number()]).optional(),
      address: z.object({
        street: z.string().optional(),
        city: z.string().optional(),
        state: z.string().optional(),
        zipcode: z.string().optional(),
        country: z.string().optional(),
      }).optional(),
    }).passthrough(), // Allow additional fields but ignore them during validation
  ]).optional().nullable(),
  company_id: z.string().optional(),
  position: z.string().optional(),
  segment_id: z.string().optional(),
  status: z.enum(["new", "contacted", "qualified", "cold", "converted", "lost", "not_qualified"]).default("new"),
  notes: z.string().optional(),
  origin: z.string().optional(),
  site_id: z.string().min(1, "Site ID is required"),
  birthday: z.string().optional(),
  language: z.string().optional(),
  social_networks: z.object({
    linkedin: z.string().optional().nullable(),
    twitter: z.string().optional().nullable(),
    facebook: z.string().optional().nullable(),
    instagram: z.string().optional().nullable(),
    tiktok: z.string().optional().nullable(),
    youtube: z.string().optional().nullable(),
    whatsapp: z.string().optional().nullable(),
    pinterest: z.string().optional().nullable(),
    threads: z.string().optional().nullable(),
  }).optional(),
  address: z.object({
    street: z.string().optional(),
    city: z.string().optional(),
    state: z.string().optional(),
    zipcode: z.string().optional(),
    country: z.string().optional(),
  }).optional(),
  assignee_id: z.string().optional().nullable(),
  buyer_user_id: z.string().optional().nullable(),
})

export type CreateLeadInput = z.infer<typeof CreateLeadSchema>

// Schema para validar los datos de entrada al actualizar un lead
export const UpdateLeadSchema = z.object({
  id: z.string().min(1, "ID is required"),
  name: z.string().min(1).optional(),
  email: z.union([z.string().email(), z.literal(""), z.null()]).optional(),
  personal_email: z.union([z.string().email(), z.literal(""), z.null()]).optional().nullable(),
  phone: z.string().optional().nullable(),
  company: z.union([
    z.string(),
    z.object({
      name: z.string().optional(),
      website: z.string().optional(),
      industry: z.string().optional(),
      size: z.string().optional(),
      annual_revenue: z.string().optional(),
      founded: z.string().optional(),
      description: z.string().optional(),
      domain: z.string().optional(),
      location: z.any().optional(), // Allow any location structure
      external_organization_id: z.union([z.string(), z.number()]).optional(),
      address: z.object({
        street: z.string().optional(),
        city: z.string().optional(),
        state: z.string().optional(),
        zipcode: z.string().optional(),
        country: z.string().optional(),
      }).optional(),
    }).passthrough(), // Allow additional fields but ignore them during validation
  ]).optional().nullable(),
  company_id: z.string().optional().nullable(),
  position: z.string().optional().nullable(),
  campaign_id: z.string().optional().nullable(),
  segment_id: z.string().optional().nullable(),
  status: z.enum(["new", "contacted", "qualified", "cold", "converted", "lost", "not_qualified"]).optional(),
  notes: z.string().optional().nullable(),
  origin: z.string().optional().nullable(),
  site_id: z.string().min(1, "Site ID is required"),
  birthday: z.string().optional().nullable(),
  language: z.string().optional().nullable(),
  social_networks: z.object({
    linkedin: z.string().optional().nullable(),
    twitter: z.string().optional().nullable(),
    facebook: z.string().optional().nullable(),
    instagram: z.string().optional().nullable(),
    tiktok: z.string().optional().nullable(),
    youtube: z.string().optional().nullable(),
    whatsapp: z.string().optional().nullable(),
    pinterest: z.string().optional().nullable(),
    threads: z.string().optional().nullable(),
  }).optional().nullable(),
  address: z.object({
    street: z.string().optional(),
    city: z.string().optional(),
    state: z.string().optional(),
    zipcode: z.string().optional(),
    country: z.string().optional(),
  }).optional().nullable(),
  attribution: z.object({
    user_id: z.string(),
    user_name: z.string(),
    date: z.string(),
    final_amount: z.number().optional(),
    is_market_fit_influenced: z.boolean(),
    notes: z.string().optional(),
  }).optional().nullable(),
  assignee_id: z.string().optional().nullable(),
  buyer_user_id: z.string().optional().nullable(),
})

export type UpdateLeadInput = z.infer<typeof UpdateLeadSchema>
