import { journeyStage, makeBusinessHours, makeCopywriting, weekdaySchedule } from "../factories"

const SITE = "demo-saas-en-123"
const USER = "demo-user-123"
const weekdays = ["monday", "tuesday", "wednesday", "thursday", "friday"] as string[]

export const saasContext = {
  sitesPatch: {
    description: "B2B operations platform for mid-market and enterprise revenue teams.",
    logo_url: "https://picsum.photos/seed/acme-saas-logo/200/200",
  },
  settingsPatch: {
    about: "Acme helps B2B teams qualify inbound leads, book demos, and keep implementation on track from one workspace.",
    company_size: "51-200",
    industry: "B2B SaaS",
    currency: "USD",
    default_locale: "en",
    products: [
      { name: "Starter plan", description: "Core CRM and inbox for small teams.", cost: 12, lowest_sale_price: 49, target_sale_price: 49 },
      { name: "Pro plan", description: "Automation, seats, and priority support.", cost: 28, lowest_sale_price: 149, target_sale_price: 149 },
    ],
    services: [
      { name: "Onboarding package", description: "Two-week implementation with a CSM.", cost: 800, lowest_sale_price: 2500, target_sale_price: 2500 },
      { name: "API add-on", description: "Production quota and webhooks.", cost: 20, lowest_sale_price: 99, target_sale_price: 99 },
    ],
    swot: {
      strengths: "Fast time-to-demo and a clear enterprise path.",
      weaknesses: "Implementation still depends on a small CSM bench.",
      opportunities: "Partner-led deals in logistics and fintech.",
      threats: "Incumbent suites bundling adjacent tools.",
    },
    locations: [
      {
        name: "Austin HQ",
        address: "500 W 2nd St",
        city: "Austin",
        state: "TX",
        zip: "78701",
        country: "US",
        restrictions: { enabled: false, included_addresses: [], excluded_addresses: [] },
      },
    ],
    business_hours: [
      makeBusinessHours("Headquarters", "America/Chicago", weekdaySchedule(weekdays, "09:00", "18:00")),
      makeBusinessHours("Customer success", "America/New_York", weekdaySchedule(weekdays, "08:00", "17:00")),
    ],
    marketing_budget: { total: 42000, available: 18750 },
    marketing_channels: [
      { name: "LinkedIn", type: "paid" },
      { name: "Product-led signup", type: "owned" },
      { name: "Partner webinars", type: "event" },
    ],
    social_media: [
      { platform: "linkedin", url: "https://linkedin.com/company/acme-saas", handle: "acme-saas", isActive: true },
      { platform: "x", url: "https://x.com/acmesaas", handle: "acmesaas", isActive: true },
    ],
    team_members: [
      { email: "admin@acme-saas.demo", role: "admin", name: "Demo Admin", position: "Founder" },
      { email: "sdr@acme-saas.demo", role: "create", name: "Alex Chen", position: "SDR" },
      { email: "csm@acme-saas.demo", role: "create", name: "Priya Shah", position: "CSM" },
    ],
    calendars: [
      {
        id: "cal-saas-demo",
        name: "Product demo",
        slug: "demo",
        member_ids: [USER],
        description: "Round-robin demo calendar",
        location: "Meet",
        duration: 45,
        buffer: 15,
        created_at: new Date().toISOString(),
      },
    ],
    competitors: [
      { url: "https://hubspot.com", name: "HubSpot" },
      { url: "https://salesforce.com", name: "Salesforce" },
    ],
    focus_mode: 80,
    business_model: { b2b: true, b2c: false, b2b2c: false },
    goals: {
      quarterly: "Book 40 qualified demos from inbound.",
      yearly: "Reach $1.2M ARR with a 90-day implementation SLA.",
      fiveYear: "Become the default ops layer for mid-market revenue teams.",
      tenYear: "Expand into a full customer-lifecycle suite.",
    },
    branding: {
      brand_essence: "Clarity for every revenue conversation.",
      brand_personality: "Precise, calm, and confident.",
      brand_benefits: "Shorter sales cycles and cleaner handoffs.",
      brand_attributes: "Reliable, structured, enterprise-ready.",
      brand_values: "Transparency, speed, and customer outcomes.",
      brand_promise: "Every lead has a next step by end of day.",
      brand_archetype: "sage",
      primary_color: "#0F172A",
      secondary_color: "#E2E8F0",
      accent_color: "#2563EB",
      success_color: "#16A34A",
      warning_color: "#D97706",
      error_color: "#DC2626",
      background_color: "#FFFFFF",
      surface_color: "#F8FAFC",
      primary_font: "IBM Plex Sans",
      secondary_font: "IBM Plex Serif",
      font_size_scale: "medium",
      communication_style: "professional",
      personality_traits: ["clear", "credible", "helpful"],
      emotions_to_evoke: ["confidence", "control"],
      preferred_phrases: ["Qualified next step", "Ready for demo"],
      forbidden_words: ["hack", "growth at all costs"],
      do_list: ["Lead with outcomes", "Name the buyer role"],
      dont_list: ["Overclaim AI magic", "Use startup slang in enterprise copy"],
    },
    customer_journey: {
      awareness: journeyStage(["LinkedIn ads", "Partner webinars"], ["Impressions"], ["Publish comparison posts"]),
      consideration: journeyStage(["Case studies", "ROI calculator"], ["Demo requests"], ["Send brief to SDR"]),
      decision: journeyStage(["Live demo", "Security review"], ["SQL rate"], ["Send enterprise quote"]),
      purchase: journeyStage(["Annual contract", "Onboarding kickoff"], ["Closed-won"], ["Assign CSM"]),
      retention: journeyStage(["QBR", "Health scores"], ["NRR"], ["Expand seats"]),
      referral: journeyStage(["Customer stories"], ["Referrals"], ["Ask champions"]),
    },
    channels: {
      website: {
        enabled: true,
        track_visitors: true,
        track_actions: true,
        record_screen: false,
        enable_chat: true,
        chat_accent_color: "#2563EB",
        allow_anonymous_messages: false,
        chat_position: "bottom-right",
        welcome_message: "Want a demo? Share your team size and we will route you.",
        chat_title: "Acme concierge",
      },
    },
    shop: null,
    printers: { devices: [] },
    activities: {
      daily_resume_and_stand_up: { status: "default" },
      local_lead_generation: { status: "inactive" },
      icp_lead_generation: { status: "default" },
      leads_initial_cold_outreach: { status: "default" },
      leads_follow_up: { status: "default" },
      email_sync: { status: "default" },
      assign_leads_to_team: { status: "active" },
      notify_team_on_inbound_conversations: { status: "default" },
      supervise_conversations: { status: "active" },
    },
  },
  copywriting: [
    makeCopywriting({
      id: "copy-saas-1",
      siteId: SITE,
      userId: USER,
      title: "Inbound qualify note",
      content: "Thanks for reaching out. If you share team size and CRM, I can book a 45-minute demo this week.",
      copy_type: "linkedin_message",
      target_audience: "Inbound leads",
      use_case: "Qualification",
      tags: ["sdr", "inbound"],
    }),
    makeCopywriting({
      id: "copy-saas-2",
      siteId: SITE,
      userId: USER,
      title: "Demo follow-up",
      content: "Recap from today: Pro plan, SSO, and a two-week onboarding package. Quote attached for 14 days.",
      copy_type: "follow_up_email",
      target_audience: "Qualified leads",
      use_case: "Post-demo",
      tags: ["csm", "quote"],
    }),
  ],
}
